use super::world::{AlbumRecord, ChallengeRecord, InteractRecord};

mod activities;
mod communication;
mod equipment;
mod inventory;
mod profile;
mod progression;
mod world_state;

pub use activities::*;
pub use communication::*;
pub use equipment::*;
pub use inventory::*;
pub use profile::*;
pub use progression::*;
pub use world_state::*;

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct PlayerRecord {
    pub uid: i64,
    pub username: String,
    pub nickname: String,
    pub level: i32,
    pub gameplay_id: i32,
    pub created_at: i32,
    pub last_login_time: i32,
    pub cur_form: i32,
    pub profile_avatar: i32,
    pub profile_card: i32,
    pub profile_title: i32,
    pub profile_frame: i32,
    pub banner_girl: i32,
    pub traced_task_group: i32,
    pub heat_updated_at: i32,
    pub profile_unlocks: Vec<ProfileUnlockRecord>,
    pub skins: Vec<i32>,
    pub ship_tags: Vec<i32>,
    pub archive_unlocks: Vec<ArchiveUnlockRecord>,
    pub region: i32,
    pub city_guides: Vec<String>,
    pub user_guides: Vec<String>,
    pub locals: Vec<LocalRecord>,
    pub favors: Vec<FavorRecord>,
    pub favor_day: i32,
    pub favor_touches: i32,
    pub sms: Vec<SmsRecord>,
    pub items: Vec<ItemRecord>,
    pub item_acquired: Vec<ItemAcquiredRecord>,
    pub item_spent: Vec<ItemSpentRecord>,
    pub partners: Vec<PartnerRecord>,
    pub equips: Vec<EquipRecord>,
    pub equipment_groups: Vec<EquipmentGroupRecord>,
    pub team_cores: Vec<TeamCoreRecord>,
    pub team_equips: Vec<TeamEquipRecord>,
    pub skillstones: Vec<SkillStoneRecord>,
    pub feats: Vec<FeatRecord>,
    pub collections: Vec<CollectionRecord>,
    pub collection_suit_rewards: Vec<CollectionSuitRewardRecord>,
    pub collection_places: Vec<CollectionPlaceRecord>,
    pub tp_map: Vec<TpMapRecord>,
    pub role_attrs: Vec<RoleAttrRecord>,
    pub playing_port: Option<PlayingPortRecord>,
    pub version_task_claims: Vec<i32>,
    pub missions: Vec<MissionRecord>,
    pub formations: Vec<FormationRecord>,
    pub tasks: Vec<TaskRecord>,
    pub ports: Vec<PortRecord>,
    pub completed_dungeons: Vec<i32>,
    pub dungeon_clears: Vec<DungeonClearRecord>,
    pub role_progress: Vec<RoleProgressRecord>,
    pub daily_day: i32,
    pub daily_activity: i32,
    pub daily_reward_progress: i32,
    pub heat_exchange_day: i32,
    pub heat_exchange_count: i32,
    pub daily_tasks: Vec<DailyTaskRecord>,
    pub gold_coins: Vec<GoldCoinRecord>,
    pub collection_resources: Vec<CollectionResourceRecord>,
    pub monster_points: Vec<MonsterPointRecord>,
    pub monster_manuals: Vec<MonsterManualRecord>,
    pub region_coin_daily: Vec<RegionCoinDailyRecord>,
    pub region_ticket_day: i32,
    pub region_levels: Vec<RegionProgressRecord>,
    pub reward_boxes: Vec<RewardBoxRecord>,
    pub achievements: Vec<AchievementRecord>,
    pub activity_7day_claims: Vec<Activity7DayClaimRecord>,
    pub activity_7day_point_claims: Vec<i32>,
    pub activity_level_rewards: Vec<i32>,
    pub activity_limited_level_rewards: Vec<i32>,
    pub activity_challenge_point_claims: Vec<i32>,
    pub battle_pass: BattlePassRecord,
    pub mall_purchases: Vec<MallPurchaseRecord>,
    pub recharge_purchases: Vec<RechargePurchaseRecord>,
    pub boss_rush: BossRushRecord,
    pub activity_boss: ActivityBossRecord,
    pub version_challenges: Vec<VersionChallengeRecord>,
    pub version_challenge_rewards: Vec<i32>,
    pub more_team_challenges: Vec<MoreTeamChallengeRecord>,
    pub more_team_challenge_rewards: Vec<i32>,
    pub rift: RiftRecord,
    pub rouge_progress: Vec<RougeProgressRecord>,
    pub rouge_technology: Vec<i32>,
    pub rouge_score: i32,
    pub rouge_score_point_at: i32,
    pub rouge_run: Option<Vec<u8>>,
    pub gachas: Vec<GachaRecord>,
    pub gacha_logs: Vec<GachaLogRecord>,
    pub checkins: Vec<CheckinRecord>,
    pub checked_red_dots: Vec<String>,
    pub mails: Vec<MailRecord>,
    pub interact_objs: Vec<InteractRecord>,
    pub challenges: Vec<ChallengeRecord>,
    pub albums: Vec<AlbumRecord>,
    pub dense_fogs: Vec<i32>,
}
