use protocol::proids::Id;

use crate::handlers::{
    activity, activity_boss, activity_challenge, album, archive, battle_pass, boss_rush,
    city_guide, collection, collection_resource, dungeon, equipment, exchange, favor, formation,
    gacha, gold_coin, guide, inventory, local, maid, mail, main_city, mall, map, missions, monster,
    more_team_challenge, partner, playing_port, profile, progression, red_dot, region, reward_box,
    rift, rogue, role_attr, role_customization, roles, skillstone, sms, social, system, tasks,
    team_core, team_equip, trial, user, version_challenge,
};

use super::{context::HandlerContext, error::NetworkResult, packet::ClientPacket};

macro_rules! dispatch {
    ($cmd_id:expr, $ctx:expr, $request:expr, {
        $($variant:path => $handler:expr),* $(,)?
    }) => {
        match $cmd_id {
            $(
                $variant => {
                    $handler($ctx, $request).await?;
                    Ok(true)
                },
            )*
            _ => Ok(false),
        }
    };
}

pub(super) async fn dispatch_command(
    ctx: &mut HandlerContext,
    request: ClientPacket,
) -> NetworkResult<bool> {
    let Ok(cmd_id) = Id::try_from(i32::from(request.proto_id)) else {
        return Ok(false);
    };

    dispatch!(cmd_id, ctx, request, {
        Id::DcNetWorkingParamItemsGet => inventory::on_list,
        Id::DcNetWorkingParamItemsUseItem => inventory::on_use,
        Id::DcNetWorkingParamItemsConvert => inventory::on_convert,
        Id::DcNetWorkingParamItemsSynthesis => inventory::on_synthesis,
        Id::DcNetWorkingParamItemSelectReward => inventory::on_select_reward,
        Id::DcNetWorkingParamRebateItemUse => inventory::on_rebate_item_use,
        Id::DcNetWorkingParamGachaGetList => gacha::on_list,
        Id::DcNetWorkingParamGachaDo => gacha::on_draw,
        Id::DcNetWorkingParamGachaLogs => gacha::on_history,
        Id::DcNetWorkingParamGachaClaimCumReward => gacha::on_claim_cumulative,
        Id::DcNetWorkingParamGachaClaimExtra => gacha::on_claim_extra,
        Id::DcNetWorkingParamFormationSet => formation::on_set,
        Id::DcNetWorkingParamFormationAdd => formation::on_add,
        Id::DcNetWorkingParamFormationDel => formation::on_delete,
        Id::DcNetWorkingParamMissonsList => missions::on_list,
        Id::DcNetWorkingParamMissonsTakeReward => missions::on_take_reward,
        Id::DcNetWorkingParamMonstersMonsterManual4Port => monster::on_manual_list,
        Id::DcNetWorkingParamMonsterPoints => monster::on_points,
        Id::DcNetWorkingParamMonsterPointHit => monster::on_point_hit,
        Id::DcNetWorkingParamRolesUserRoles => roles::on_user_roles,
        Id::DcNetWorkingParamRolesChangeSkin => roles::on_change_skin,
        Id::DcNetWorkingParamRolesChangeAppear => role_customization::on_change_appearance,
        Id::DcNetWorkingParamRolesChangeElement => role_customization::on_change_element,
        Id::DcNetWorkingParamRolesChangeElement4Call => role_customization::on_change_call_element,
        Id::DcNetWorkingParamRolesProfile => role_customization::on_profiles,
        Id::DcNetWorkingParamUserChangeBannerGril => role_customization::on_change_banner,
        Id::DcNetWorkingParamRolesMcSwitch => role_customization::on_mc_switch,
        Id::DcNetWorkingParamRolesRankUp => roles::on_rank_up,
        Id::DcNetWorkingParamRolesBrekUp => roles::on_resonance,
        Id::DcNetWorkingParamRoleRankUpAward => roles::on_rank_reward,
        Id::DcNetWorkingParamRolesLevelUp => roles::on_level_up,
        Id::DcNetWorkingParamTalentLevelUp => roles::on_talent_level_up,
        Id::DcNetWorkingParamEquipsList => equipment::on_list,
        Id::DcNetWorkingParamEquipsLevelUp => equipment::on_level_up,
        Id::DcNetWorkingParamEquipsSet => equipment::on_set,
        Id::DcNetWorkingParamEquipsUnset => equipment::on_unset,
        Id::DcNetWorkingParamEquipsSwap => equipment::on_swap,
        Id::DcNetWorkingParamEquipsLock => equipment::on_lock,
        Id::DcNetWorkingParamEquipsRandomWordRefresh => equipment::on_random_word_refresh,
        Id::DcNetWorkingParamEquipsRandomWordReplace => equipment::on_random_word_replace,
        Id::DcNetWorkingParamEquipsEquipSetGroup => equipment::on_set_group,
        Id::DcNetWorkingParamEquipsEquipGetGroup => equipment::on_group_list,
        Id::DcNetWorkingParamEquipsEquipDelGroup => equipment::on_delete_group,
        Id::DcNetWorkingParamEquipsSetEquips => equipment::on_set_equips,
        Id::DcNetWorkingParamPartnerList => partner::on_list,
        Id::DcNetWorkingParamPartnerLvUp => partner::on_level_up,
        Id::DcNetWorkingParamPartnerBrek => partner::on_break,
        Id::DcNetWorkingParamPartnerSkillUp => partner::on_skill_up,
        Id::DcNetWorkingParamPartnerImpress => partner::on_impress,
        Id::DcNetWorkingParamPartnerChange => partner::on_change,
        Id::DcNetWorkingParamPartnerUnset => partner::on_unset,
        Id::DcNetWorkingParamPartnerSwap => partner::on_swap,
        Id::DcNetWorkingParamPartnerLock => partner::on_lock,
        Id::DcNetWorkingParamFormationList => formation::on_list,
        Id::DcNetWorkingParamFeatList => progression::on_feature_list,
        Id::DcNetWorkingParamPortList => progression::on_port_list,
        Id::DcNetWorkingParamPortsStart => progression::on_port_start,
        Id::DcNetWorkingParamPortsSett => progression::on_port_settlement,
        Id::DcNetWorkingParamFormationCurSet => formation::on_select,
        Id::DcNetWorkingParamSysInfo => system::on_info,
        Id::DcNetWorkingParamTaskList => tasks::on_list,
        Id::DcNetWorkingParamTask2Done => tasks::on_complete,
        Id::DcNetWorkingParamTaskGoalSet => tasks::on_goal_set,
        Id::DcNetWorkingParamRoleSkinGetList => maid::on_skin_list,
        Id::DcNetWorkingParamDungeonStart => dungeon::on_start,
        Id::DcNetWorkingParamDungeonSett => dungeon::on_settlement,
        Id::DcNetWorkingParamDungeonList => dungeon::on_list,
        Id::DcNetWorkingParamDungeonSweep => dungeon::on_sweep,
        Id::DcNetWorkingParamLocalSet => local::on_set,
        Id::DcNetWorkingParamLocalList => local::on_list,
        Id::DcNetWorkingParamCityGuideSet => city_guide::on_set,
        Id::DcNetWorkingParamCityGuideList => city_guide::on_list,
        Id::DcNetWorkingParamFriendsInfo => social::on_info,
        Id::DcNetWorkingParamFriendGiftSend => social::on_send_gift,
        Id::DcNetWorkingParamFriendGiftClaim => social::on_claim_gift,
        Id::DcNetWorkingParamFriendsSearch => social::on_search,
        Id::DcNetWorkingParamFriendsRequest => social::on_request,
        Id::DcNetWorkingParamFriendsApprove => social::on_approve,
        Id::DcNetWorkingParamFriendsDelete => social::on_delete,
        Id::DcNetWorkingParamFriendsProfile => social::on_profile,
        Id::DcNetWorkingParamEmailsGetEmails => mail::on_list,
        Id::DcNetWorkingParamEmailsRead => mail::on_read,
        Id::DcNetWorkingParamEmailsTakeGift => mail::on_claim_attachments,
        Id::DcNetWorkingParamEmailsDelete => mail::on_delete,
        Id::DcNetWorkingParamInteractObjs => main_city::on_interact_list,
        Id::DcNetWorkingParamInteracting => main_city::on_interact,
        Id::DcNetWorkingParamChallengesList => main_city::on_challenge_list,
        Id::DcNetWorkingParamChallengesReport => main_city::on_challenge_report,
        Id::DcNetWorkingParamChallengesParkourReport => main_city::on_parkour_report,
        Id::DcNetWorkingParamDenseFogList => map::on_dense_fog_list,
        Id::DcNetWorkingParamDenseFogSet => map::on_dense_fog_set,
        Id::DcNetWorkingParamPlayingPortSet => playing_port::on_update,
        Id::DcNetWorkingParamPlayingPortGet => playing_port::on_list,
        Id::DcNetWorkingParamAlbumsList => album::on_list,
        Id::DcNetWorkingParamAlbumsSelect => album::on_select,
        Id::DcNetWorkingParamTBoxInfoList => reward_box::on_list,
        Id::DcNetWorkingParamTBoxTakeReward => reward_box::on_claim,
        Id::DcNetWorkingParamRBoxInfoList => reward_box::on_refresh_list,
        Id::DcNetWorkingParamRBoxTakeReward => reward_box::on_refresh_box_reward,
        Id::DcNetWorkingParamTpMapInfoList => map::on_teleport_list,
        Id::DcNetWorkingParamTpMapSet => map::on_teleport_update,
        Id::DcNetWorkingParamFavorList => favor::on_favor_list,
        Id::DcNetWorkingParamFavorAdd => favor::on_add,
        Id::DcNetWorkingParamFavorUseItem => favor::on_use_item,
        Id::DcNetWorkingParamSmsList => sms::on_list,
        Id::DcNetWorkingParamSmsRead => sms::on_read,
        Id::DcNetWorkingParamShopGetInfo => mall::on_shop_info,
        Id::DcNetWorkingParamShopGetGoods => mall::on_shop_goods,
        Id::DcNetWorkingParamShopBuy => mall::on_shop_buy,
        Id::DcNetWorkingParamShopSell => mall::on_shop_sell,
        Id::DcNetWorkingParamShopSetShipTags => mall::on_set_ship_tags,
        Id::DcNetWorkingParamShopShipTagRefresh => mall::on_ship_tag_refresh,
        Id::DcNetWorkingParamExchangeInfo => exchange::on_info,
        Id::DcNetWorkingParamExchangePhy => exchange::on_heat,
        Id::DcNetWorkingParamExchangeSbs2hhs => exchange::on_diamond_to_stamp,
        Id::DcNetWorkingParamRegionInfo => region::on_info,
        Id::DcNetWorkingParamRegionTakeDailyReward => region::on_take_daily_reward,
        Id::DcNetWorkingParamRegionTakeTask => region::on_take_task,
        Id::DcNetWorkingParamRegionList => region::on_list,
        Id::DcNetWorkingParamGoldCoinList => gold_coin::on_list,
        Id::DcNetWorkingParamGoldCoinCollect => gold_coin::on_collect,
        Id::DcNetWorkingParamCollectionResList => collection_resource::on_list,
        Id::DcNetWorkingParamCollectionResCollect => collection_resource::on_collect,
        Id::DcNetWorkingParamMallList => mall::on_mall_list,
        Id::DcNetWorkingParamMallBuy => mall::on_mall_buy,
        Id::DcNetWorkingParamRechargeList => mall::on_recharge_list,
        Id::DcNetWorkingParamTrialSave => trial::on_save,
        Id::DcNetWorkingParamTrialDone => trial::on_complete,
        Id::DcNetWorkingParamTrialInfo => trial::on_info,
        Id::DcNetWorkingParamTrialList => trial::on_list,
        Id::DcNetWorkingParamArchiveList => archive::on_archive_list,
        Id::DcNetWorkingParamAchiList => archive::on_achievement_list,
        Id::DcNetWorkingParamAchiClaim => archive::on_achievement_claim,
        Id::DcNetWorkingParamCollectionList => collection::on_list,
        Id::DcNetWorkingParamCollectionReward => collection::on_reward,
        Id::DcNetWorkingParamCollectionSuitRewardList => collection::on_suit_list,
        Id::DcNetWorkingParamCollectionSuitReward => collection::on_suit_reward,
        Id::DcNetWorkingParamCollectionPlace => collection::on_place,
        Id::DcNetWorkingParamCollectionPlaceInfos => collection::on_place_list,
        Id::DcNetWorkingParamTaskCycleList => tasks::on_cycle_list,
        Id::DcNetWorkingParamTaskCycleTakeActivity => tasks::on_cycle_take_activity,
        Id::DcNetWorkingParamTaskCycleTakeReward => tasks::on_cycle_take_reward,
        Id::DcNetWorkingParamRougeInfo => rogue::on_info,
          Id::DcNetWorkingParamRougeStart => rogue::on_start,
          Id::DcNetWorkingParamRougeFormSave => rogue::on_form_save,
          Id::DcNetWorkingParamRougeStatusSet => rogue::on_status_set,
          Id::DcNetWorkingParamRougeEnter => rogue::on_enter,
          Id::DcNetWorkingParamRougeNodeReport => rogue::on_node_report,
          Id::DcNetWorkingParamRougeBuffSelect => rogue::on_buff_select,
          Id::DcNetWorkingParamRougeWaiveBuff => rogue::on_buff_waive,
          Id::DcNetWorkingParamRougeRegenBuff => rogue::on_buff_regen,
          Id::DcNetWorkingParamRougeCoinboxOpen => rogue::on_coinbox_open,
          Id::DcNetWorkingParamRougeBossBoxOpen => rogue::on_rouge_boss_box_open,
          Id::DcNetWorkingParamRougeRest => rogue::on_rest,
          Id::DcNetWorkingParamRougeBlessOpen => rogue::on_bless_open,
          Id::DcNetWorkingParamRougeFinish => rogue::on_finish,
          Id::DcNetWorkingParamRougeTradeBuy => rogue::on_trade_buy,
          Id::DcNetWorkingParamRougeItemUse => rogue::on_item_use,
          Id::DcNetWorkingParamRougeSubevtItem => rogue::on_sub_event_item,
          Id::DcNetWorkingParamRougeSubevtStoreBuy => rogue::on_subevt_store_buy,
          Id::DcNetWorkingParamRougeNpcSelectEffect => rogue::on_npc_select_effect,
          Id::DcNetWorkingParamRougeList => rogue::on_rogue_list,
          Id::DcNetWorkingParamRougeTechTree => rogue::on_tech_tree,
          Id::DcNetWorkingParamRougeTechTake => rogue::on_tech_take,
          Id::DcNetWorkingParamRougeScoreRewardClaim => rogue::on_score_reward_claim,
        Id::DcNetWorkingParamQuestionUrl => rogue::on_question_url,
        Id::DcNetWorkingParamReddotList => red_dot::on_list,
        Id::DcNetWorkingParamReddotCheck => red_dot::on_check,
        Id::DcNetWorkingParamRoleAttrList => role_attr::on_list,
        Id::DcNetWorkingParamRoleAttrSave => role_attr::on_save,
        Id::DcNetWorkingParamBattlePassInfo => battle_pass::on_info,
        Id::DcNetWorkingParamBattlePassTasks => battle_pass::on_tasks,
        Id::DcNetWorkingParamBattlePassTaskClaim => battle_pass::on_task_claim,
        Id::DcNetWorkingParamBattlePassClaim => battle_pass::on_claim,
        Id::DcNetWorkingParamBattlePassLevelUp => battle_pass::on_level_up,
        Id::DcNetWorkingParamRiftInfo => rift::on_info,
        Id::DcNetWorkingParamRiftStart => rift::on_start,
        Id::DcNetWorkingParamRiftNext => rift::on_next,
        Id::DcNetWorkingParamRiftReport => rift::on_report,
        Id::DcNetWorkingParamRiftDefeat => rift::on_defeat,
        Id::DcNetWorkingParamRiftSettlment => rift::on_settlement,
        Id::DcNetWorkingParamRiftRank => rift::on_rank,
        Id::DcNetWorkingParamRiftTask => rift::on_task,
        Id::DcNetWorkingParamRiftTaskClaim => rift::on_task_claim,
        Id::DcNetWorkingParamBossRushInfo => boss_rush::on_info,
        Id::DcNetWorkingParamBossRushSett => boss_rush::on_settlement,
        Id::DcNetWorkingParamBossRushReward => boss_rush::on_reward,
        Id::DcNetWorkingParamBossRushRank => boss_rush::on_rank,
        Id::DcNetWorkingParamBossRushResetTeam => boss_rush::on_reset_team,
        Id::DcNetWorkingParamActivityBossChallengeSett => activity_boss::on_settlement,
        Id::DcNetWorkingParamActivityBossChallengeInfo => activity_boss::on_info,
        Id::DcNetWorkingParamActivityBossChallengeReward => activity_boss::on_reward,
        Id::DcNetWorkingParamActivityBossChallengeRank => activity_boss::on_rank,
        Id::DcNetWorkingParamActivityBossChallengeStart => activity_boss::on_start,
        Id::DcNetWorkingParamActivityBossChallengeDailyReward => activity_boss::on_daily_reward,
        Id::DcNetWorkingParamActivityChallengesList => activity_challenge::on_list,
        Id::DcNetWorkingParamActivityChallengesClaim => activity_challenge::on_claim,
        Id::DcNetWorkingParamActivityChallengesPointClaim => activity_challenge::on_point_claim,
        Id::DcNetWorkingParamActivityOpenList => activity::on_open_list,
        Id::DcNetWorkingParamActivityLimitedLevelUpList => activity::on_limited_level_up_list,
        Id::DcNetWorkingParamActivityLimitedLevelUpReward => activity::on_limited_level_up_reward,
        Id::DcNetWorkingParamCheckinInfo => activity::on_check_in_info,
        Id::DcNetWorkingParamCheckinCheck => activity::on_check_in_check,
        Id::DcNetWorkingParamCheckinReward => activity::on_check_in_reward,
        Id::DcNetWorkingParamActivityLevelUpList => activity::on_level_up_list,
        Id::DcNetWorkingParamActivityLevelUpReward => activity::on_level_up_reward,
        Id::DcNetWorkingParamActivity7DayList => activity::on_seven_day_list,
        Id::DcNetWorkingParamActivity7DayClaim => activity::on_seven_day_claim,
        Id::DcNetWorkingParamActivity7DayPointClaim => activity::on_seven_day_point_claim,
        Id::DcNetWorkingParamVersionActivityInfo => activity::on_version_info,
        Id::DcNetWorkingParamVersionTaskList => activity::on_version_task_list,
        Id::DcNetWorkingParamVersionTaskClaim => activity::on_version_task_claim,
        Id::DcNetWorkingParamVersionChallengeStart => version_challenge::on_start,
        Id::DcNetWorkingParamVersionChallengeList => version_challenge::on_list,
        Id::DcNetWorkingParamVersionChallengeSett => version_challenge::on_settlement,
        Id::DcNetWorkingParamVersionChallengeAward => version_challenge::on_award,
        Id::DcNetWorkingParamVersionChallengeStageList => version_challenge::on_stage_list,
        Id::DcNetWorkingParamMoreTeamChallengeList => more_team_challenge::on_list,
        Id::DcNetWorkingParamMoreTeamChallengeSett => more_team_challenge::on_settlement,
        Id::DcNetWorkingParamMoreTeamChallengeAward => more_team_challenge::on_award,
        Id::DcNetWorkingParamMoreTeamChallengeStart => more_team_challenge::on_start,
        Id::DcNetWorkingParamMoreTeamChallengeGroupList => more_team_challenge::on_group_list,
        Id::DcNetWorkingParamTeamCoreList => team_core::on_list,
        Id::DcNetWorkingParamTeamCoreCompose => team_core::on_compose,
        Id::DcNetWorkingParamTeamCoreLock => team_core::on_lock,
        Id::DcNetWorkingParamTeamEquipList => team_equip::on_list,
        Id::DcNetWorkingParamTeamEquipEquip => team_equip::on_equip,
        Id::DcNetWorkingParamTeamEquipUnEquip => team_equip::on_unequip,
        Id::DcNetWorkingParamTeamEquipSetCore => team_equip::on_set_core,
        Id::DcNetWorkingParamTeamEquipUnSetCore => team_equip::on_unset_core,
        Id::DcNetWorkingParamTeamEquipLock => team_equip::on_lock,
        Id::DcNetWorkingParamTeamEquipLvUp => team_equip::on_level_up,
        Id::DcNetWorkingParamSkillStoneList => skillstone::on_list,
        Id::DcNetWorkingParamSkillstonesSet => skillstone::on_set,
        Id::DcNetWorkingParamSkillstonesUnset => skillstone::on_unset,
        Id::DcNetWorkingParamSkillstonesLock => skillstone::on_lock,
        Id::DcNetWorkingParamSkillstonesSwap => skillstone::on_swap,
        Id::DcNetWorkingParamFeatUnlock => progression::on_feature_unlock,
        Id::DcNetWorkingParamUserGuideSave => guide::on_save,
        Id::DcNetWorkingParamUserGuideList => guide::on_list,
        Id::DcNetWorkingParamUserGetInfo => user::on_info,
        Id::DcNetWorkingParamUserGetPhyInfo => user::on_stamina_info,
        Id::DcNetWorkingParamNaming => user::on_rename,
        Id::DcNetWorkingParamProfileList => profile::on_list,
        Id::DcNetWorkingParamProfileSet => profile::on_set,
    })
}
