use crate::models::game::player_state::{
    AchievementRecord, Activity7DayClaimRecord, ActivityBossRecord, ArchiveUnlockRecord,
    BattlePassRecord, BossRushPortRecord, BossRushRecord, CheckinRecord, CollectionPlaceRecord,
    CollectionRecord, CollectionResourceRecord, CollectionSuitRewardRecord, DailyTaskRecord,
    DungeonClearRecord, EquipRecord, EquipmentGroupRecord, FavorRecord, FeatRecord,
    FormationPositionRecord, FormationRecord, GachaLogRecord, GachaRecord, GoldCoinRecord,
    ItemAcquiredRecord, ItemRecord, ItemSpentRecord, LocalRecord, MailGiftRecord, MailRecord,
    MallPurchaseRecord, MissionRecord, MonsterManualRecord, MonsterPointRecord,
    MoreTeamChallengeRecord, PartnerRecord, PlayerRecord, PlayingPortRecord, PortRecord,
    ProfileUnlockRecord, RechargePurchaseRecord, RegionCoinDailyRecord, RegionProgressRecord,
    RewardBoxRecord, RiftRecord, RoleAttrRecord, RoleProgressRecord, RougeProgressRecord,
    SkillStoneRecord, SmsRecord, TaskRecord, TeamCoreRecord, TeamEquipRecord, TpMapRecord,
    VersionChallengeRecord,
};
use crate::models::game::world::{AlbumRecord, ChallengeRecord, InteractRecord};

use super::*;

#[tokio::test]
async fn player_round_trip() {
    let pool = crate::connect_memory().await.unwrap();
    assert!(!exists(&pool, 42).await.unwrap());
    let record = PlayerRecord {
        uid: 42,
        username: "42".into(),
        nickname: "Player42".into(),
        level: 1,
        gameplay_id: -1,
        created_at: 10,
        last_login_time: 20,
        cur_form: 1,
        profile_avatar: 16,
        profile_card: 1,
        profile_title: 1,
        profile_frame: 1,
        banner_girl: 110_100_016,
        traced_task_group: 150_000_100,
        heat_updated_at: 123,
        profile_unlocks: vec![ProfileUnlockRecord {
            profile_type: 2,
            profile_id: 101_102_011,
        }],
        skins: vec![110_400_801],
        ship_tags: vec![1, 2, 3],
        archive_unlocks: vec![ArchiveUnlockRecord {
            archive_id: 3001,
            unlocked_at: 25,
        }],
        region: 3,
        city_guides: vec!["guide_prologue_move".into()],
        user_guides: vec!["guide_first_battle".into()],
        locals: vec![LocalRecord {
            region: 3,
            local: "4".into(),
            local2: "5".into(),
        }],
        favors: vec![FavorRecord {
            character_id: 110_300_013,
            level: 2,
            exp: 20,
        }],
        favor_day: 20_328,
        favor_touches: 3,
        sms: vec![SmsRecord {
            group_id: 410_101,
            read: true,
            selected: vec![2],
        }],
        items: vec![ItemRecord {
            user_item_id: 42_100_100_008,
            item_id: 100_100_008,
            amount: 240,
            remain_sec: 0,
            quality: 3,
        }],
        item_acquired: vec![ItemAcquiredRecord {
            item_id: 100_100_008,
            amount: 180,
        }],
        item_spent: vec![ItemSpentRecord {
            item_id: 100_100_008,
            amount: 40,
        }],
        partners: vec![PartnerRecord {
            brek: 0,
            exp: 0,
            group_id: 0,
            id: 420_400_026,
            locked: 0,
            lv: 1,
            partner_id: 100_400_026,
            quality: 5,
            reson_lv: 1,
            skill_lv: 1,
            creat_at: 30,
        }],
        equips: vec![EquipRecord {
            equip_id: 100_500_114,
            exp: 0,
            user_equip_id: 420_500_114,
            in_group: 0,
            locked: 0,
            level: 0,
            equiped_role: 0,
            pos: 1,
            main_words_id: 1,
            deputy_words_id: vec![2, 3],
            quality: 4,
            random_words_id: vec![1001],
            planned_words_id: vec![4],
            minnum: 0,
            tmp_word: 0,
            tmp_word_idx: -1,
            creat_at: 30,
        }],
        equipment_groups: vec![EquipmentGroupRecord {
            id: 1,
            game_role_id: 110_100_016,
            group_name: "boss".into(),
            user_equip_ids: vec![420_500_114],
        }],
        team_cores: vec![TeamCoreRecord {
            pos: 0,
            id: 42_100_900_001,
            locked: true,
            equipped_id: 0,
            core_id: 100_900_001,
        }],
        team_equips: vec![TeamEquipRecord {
            equipped_formation_id: 1,
            id: 42_100_800_011,
            locked: true,
            team_equip_id: 100_800_011,
            level: 2,
            exp: 10,
            main_words_id: 100_801_016,
            pos_num: 3,
        }],
        skillstones: vec![SkillStoneRecord {
            pos: 2,
            user_stone_id: 42_100_600_116,
            locked: true,
            equipped_role: 110_100_001,
            stone_id: 100_600_116,
            quality: 6,
        }],
        feats: vec![FeatRecord { id: 19, status: 1 }],
        collections: vec![CollectionRecord {
            cid: 100_700_016,
            in_time: 30,
            reward: false,
        }],
        collection_suit_rewards: vec![CollectionSuitRewardRecord {
            suit_id: 10_070_005,
            step: 1,
        }],
        collection_places: vec![CollectionPlaceRecord {
            collection_id: 100_700_016,
            platform_id: 2,
        }],
        tp_map: vec![TpMapRecord {
            key: "nh_prologue_tp1".into(),
            value: "1".into(),
        }],
        role_attrs: vec![RoleAttrRecord {
            role_id: 110_100_016,
            mp: 10,
            ep: 20,
            hp: 30,
        }],
        playing_port: Some(PlayingPortRecord {
            port_index_id: 140_301_056,
            port_info: "checkpoint".into(),
        }),
        version_task_claims: vec![10_030_101],
        missions: vec![MissionRecord {
            misson_id: 1,
            total_num: 1,
            curr_num: 1,
            taken: false,
            take_time: 0,
            mission_type: 1,
            created_at: 10,
        }],
        formations: vec![FormationRecord {
            formation_id: 1,
            remark: String::new(),
            positions: vec![FormationPositionRecord {
                game_role_id: 110_100_016,
                key_num: 2,
            }],
        }],
        tasks: vec![TaskRecord {
            id: 1_500_000_000,
            status: 2,
            picked_at: 10,
            progress: 0,
            total: 0,
        }],
        interact_objs: vec![InteractRecord {
            object_id: "switch".into(),
            interactive: false,
            status: 1,
            count: 1,
        }],
        challenges: vec![ChallengeRecord {
            id: "jump".into(),
            stars: 2,
            finished: true,
            claimed: false,
        }],
        albums: vec![AlbumRecord {
            id: 1000,
            status: 2,
            sort: 0,
        }],
        dense_fogs: vec![4_010_661],
        ports: vec![PortRecord {
            id: 180_101_056,
            pass_cnt: 1,
            is_c: true,
            is_f: false,
            port_id: 140_301_056,
            s1: 1,
            s2: 0,
            s3: 0,
            t_cnt: 0,
            updated_at: 0,
            all_cnt: 1,
        }],
        completed_dungeons: vec![180_200_001],
        dungeon_clears: vec![DungeonClearRecord {
            dungeon_type: 2,
            count: 1,
        }],
        role_progress: vec![RoleProgressRecord {
            role_id: 110_100_016,
            level: 2,
            exp: 60,
            user_partner_id: 420_400_026,
            position: 1,
            maid_qua: 2,
            skin_id: 110_400_801,
            appear_skill_key: 1,
            element: 3,
            element4call: 2,
            cur_mc: true,
            awards: vec![0],
            talents: vec![(1, 2), (2, 1)],
        }],
        daily_day: 20_328,
        daily_activity: 100,
        daily_reward_progress: 1,
        heat_exchange_day: 20_328,
        heat_exchange_count: 2,
        daily_tasks: vec![DailyTaskRecord {
            id: 1,
            taken: true,
            progress: 1,
            total: 1,
        }],
        gold_coins: vec![GoldCoinRecord {
            city_id: 140_101_056,
            coin_id: "nh_tower_cion_8".into(),
        }],
        collection_resources: vec![CollectionResourceRecord {
            collection_id: "nh_tower_collection_01".into(),
            remaining: 1,
        }],
        monster_points: vec![MonsterPointRecord {
            day: 20_328,
            point_id: "nh_field_a_group_01_p1".into(),
        }],
        monster_manuals: vec![MonsterManualRecord {
            gameplay_id: 180_101_070,
            enemy_hash: 4_199_272_699,
        }],
        region_coin_daily: vec![RegionCoinDailyRecord {
            day: 20_328,
            coin_id: 100_100_201,
            amount: 10,
        }],
        region_ticket_day: 20_328,
        region_levels: vec![RegionProgressRecord {
            region_id: 3,
            level: 2,
        }],
        reward_boxes: vec![RewardBoxRecord {
            id: "nh_field_a_RewardBox_05".into(),
            status: 1,
        }],
        achievements: vec![AchievementRecord {
            id: 500_101,
            took_at: 123,
        }],
        activity_7day_claims: vec![Activity7DayClaimRecord {
            id: 3,
            took_at: 124,
        }],
        activity_7day_point_claims: vec![1],
        activity_level_rewards: vec![1],
        activity_limited_level_rewards: vec![2],
        activity_challenge_point_claims: vec![7],
        battle_pass: BattlePassRecord {
            id: 1003,
            paid_status: 0,
            level: 1,
            exp: 525,
            exp_week: 525,
            week: 2,
            rewards: vec![(1, 1)],
            tasks: vec![10_031_010, 10_031_040],
        },
        mall_purchases: vec![MallPurchaseRecord {
            goods_id: 70_010_701,
            bought: 1,
            period: 20_328,
        }],
        recharge_purchases: vec![RechargePurchaseRecord {
            recharge_id: 201,
            purchase_count: 2,
            last_bought_at: 20_000,
            expires_at: 2_612_000,
        }],
        boss_rush: BossRushRecord {
            id: 1005,
            ports: vec![BossRushPortRecord {
                pid: 180_800_002,
                role_ids: vec![110_100_016],
                damage: 40_000,
            }],
            rewards: vec![41],
            ranking_rewards: vec![1004],
        },
        activity_boss: ActivityBossRecord {
            aid: 7,
            day: 2,
            damage: 12_000,
            daily_damage: 10_000,
            role_ids: vec![110_100_001, 110_100_002],
            rewards: vec![1],
            daily_rewards: vec![(1, 1), (2, 0)],
        },
        version_challenges: vec![VersionChallengeRecord {
            id: 37,
            star1: true,
            star2: false,
            star3: true,
        }],
        version_challenge_rewards: vec![109],
        more_team_challenges: vec![MoreTeamChallengeRecord {
            id: 1,
            cost_time: 80,
            star1: true,
            star2: true,
            star3: true,
            cycle: -1,
        }],
        more_team_challenge_rewards: vec![1],
        rift: RiftRecord {
            id: 8,
            current_port_id: 180_706_004,
            best_buff_score: 18,
            best_score: 12_000,
            best_stage: 4,
            completion_count: 2,
            run_buff_score: 12,
            run_score: 4_000,
            run_duration: 93,
            active: true,
            roles: vec![110_100_016],
            tasks: vec![6001, 6004],
        },
        rouge_progress: vec![RougeProgressRecord { id: 1, pass: 2 }],
        rouge_technology: vec![1, 3],
        rouge_score: 1500,
        rouge_score_point_at: 2,
        rouge_run: Some(vec![8, 1]),
        gachas: vec![GachaRecord {
            gacha_id: 2,
            all_count: 1,
            gacha_count_10: 0,
            reward_cnt: 1,
            reward_num: 0,
            taken_new_reward: false,
            had_take_reward: false,
        }],
        gacha_logs: vec![GachaLogRecord {
            gacha_id: 2,
            reward: 110_100_010,
            created_at: 1_787_523_760,
        }],
        checkins: vec![CheckinRecord {
            aid: 1003,
            check_days: 1,
            last_check_day: 20_328,
            claimed_days: vec![1],
        }],
        checked_red_dots: vec!["28_101000016".into()],
        mails: vec![MailRecord {
            email_id: 7,
            is_read: 1,
            taken: 1,
            sent_at: 100,
            sender: 2,
            title: "Compensation".into(),
            content: "Thanks".into(),
            gifts: vec![MailGiftRecord {
                reward: 100_100_002,
                reward_type: 0,
                amount: 300,
            }],
            expires_at: 200,
            sys_mail_id: 0,
            parameter: String::new(),
        }],
    };

    save(&pool, &record).await.unwrap();
    assert!(exists(&pool, 42).await.unwrap());
    assert_eq!(load(&pool, 42).await.unwrap(), Some(record));

    let record = load(&pool, 42).await.unwrap().unwrap();
    save(&pool, &record).await.unwrap();
    assert_eq!(load(&pool, 42).await.unwrap(), Some(record));
}
