// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct C2gHeartbeat {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct G2cHeartbeat {
    #[prost(uint32, tag = "1")]
    pub ret: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct C2gGetSeed {
    #[prost(int32, tag = "1")]
    pub send_seed: i32,
    #[prost(int32, tag = "2")]
    pub receive_seed: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct G2cGetSeed {
    #[prost(uint32, tag = "1")]
    pub ret: u32,
    #[prost(int32, tag = "2")]
    pub send_seed: i32,
    #[prost(int32, tag = "3")]
    pub receive_seed: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct C2gConnectGameServer {
    #[prost(int64, tag = "1")]
    pub uid: i64,
    #[prost(string, tag = "2")]
    pub sid: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct G2cConnectGameServer {
    #[prost(uint32, tag = "1")]
    pub ret: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct G2cBroadcast {
    #[prost(int32, tag = "1")]
    pub msg_type: i32,
    #[prost(string, tag = "2")]
    pub msg_data: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct C2gReconnect {
    #[prost(int32, tag = "1")]
    pub send_seed: i32,
    #[prost(int32, tag = "2")]
    pub receive_seed: i32,
    #[prost(int64, tag = "3")]
    pub uid: i64,
    #[prost(string, tag = "4")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct G2cReconnect {
    #[prost(uint32, tag = "1")]
    pub ret: u32,
    #[prost(int32, tag = "2")]
    pub send_seed: i32,
    #[prost(int32, tag = "3")]
    pub receive_seed: i32,
    #[prost(uint32, tag = "4")]
    pub last_timestamp: u32,
    #[prost(bytes = "vec", tag = "5")]
    pub cache_msg: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct G2cCommonErr {
    #[prost(int32, tag = "1")]
    pub pid: i32,
    #[prost(int32, tag = "2")]
    pub code: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Id {
    C2gHeartbeatId = 0,
    G2cHeartbeatId = 1,
    C2gGetSeedId = 2,
    G2cGetSeedId = 3,
    C2gConnectGameServerId = 4,
    G2cConnectGameServerId = 5,
    C2gReconnectId = 6,
    G2cReconnectId = 7,
    G2cBroadcastId = 99,
    G2cFragmentationId = 100,
    G2cCommonErrId = 999,
}
impl Id {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::C2gHeartbeatId => "C2G_HeartbeatID",
            Self::G2cHeartbeatId => "G2C_HeartbeatID",
            Self::C2gGetSeedId => "C2G_GetSeedID",
            Self::G2cGetSeedId => "G2C_GetSeedID",
            Self::C2gConnectGameServerId => "C2G_ConnectGameServerID",
            Self::G2cConnectGameServerId => "G2C_ConnectGameServerID",
            Self::C2gReconnectId => "C2G_ReconnectID",
            Self::G2cReconnectId => "G2C_ReconnectID",
            Self::G2cBroadcastId => "G2C_BroadcastID",
            Self::G2cFragmentationId => "G2C_FragmentationID",
            Self::G2cCommonErrId => "G2C_CommonErrID",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "C2G_HeartbeatID" => Some(Self::C2gHeartbeatId),
            "G2C_HeartbeatID" => Some(Self::G2cHeartbeatId),
            "C2G_GetSeedID" => Some(Self::C2gGetSeedId),
            "G2C_GetSeedID" => Some(Self::G2cGetSeedId),
            "C2G_ConnectGameServerID" => Some(Self::C2gConnectGameServerId),
            "G2C_ConnectGameServerID" => Some(Self::G2cConnectGameServerId),
            "C2G_ReconnectID" => Some(Self::C2gReconnectId),
            "G2C_ReconnectID" => Some(Self::G2cReconnectId),
            "G2C_BroadcastID" => Some(Self::G2cBroadcastId),
            "G2C_FragmentationID" => Some(Self::G2cFragmentationId),
            "G2C_CommonErrID" => Some(Self::G2cCommonErrId),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Errorcode {
    ErrSys = 0,
    ErrOk = 1,
    ErrNoSession = 2,
    ErrDiffIp = 3,
}
impl Errorcode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ErrSys => "ERR_Sys",
            Self::ErrOk => "ERR_Ok",
            Self::ErrNoSession => "ERR_NO_SESSION",
            Self::ErrDiffIp => "ERR_DIFF_IP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ERR_Sys" => Some(Self::ErrSys),
            "ERR_Ok" => Some(Self::ErrOk),
            "ERR_NO_SESSION" => Some(Self::ErrNoSession),
            "ERR_DIFF_IP" => Some(Self::ErrDiffIp),
            _ => None,
        }
    }
}
