// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ErrorInfos {
    #[prost(int32, tag = "1")]
    pub pid: i32,
    #[prost(int32, tag = "2")]
    pub code: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRedDot {
    #[prost(string, tag = "1")]
    pub arg: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_checked: bool,
    #[prost(enumeration = "Reddot", tag = "3")]
    pub func_id: i32,
    #[prost(string, tag = "4")]
    pub id: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub expire_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataReddotCheckParams {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataNotice {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub html_url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub title: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub importent: i32,
    #[prost(int32, tag = "5")]
    pub priority: i32,
    #[prost(int32, tag = "6")]
    pub send_at: i32,
    #[prost(int32, tag = "7")]
    pub end_at: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Reddot {
    Reddot = 0,
    Item = 1,
    Port = 10,
    Feat = 19,
    Rolefile = 20,
    Partner = 22,
    Equip = 23,
    Stone = 24,
    Archive = 25,
    Gacha = 26,
    Album = 27,
    Avatar = 28,
    Frame = 29,
    Card = 30,
    Title = 31,
}
impl Reddot {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Reddot => "reddot_",
            Self::Item => "reddot_item",
            Self::Port => "reddot_port",
            Self::Feat => "reddot_feat",
            Self::Rolefile => "reddot_rolefile",
            Self::Partner => "reddot_partner",
            Self::Equip => "reddot_equip",
            Self::Stone => "reddot_stone",
            Self::Archive => "reddot_archive",
            Self::Gacha => "reddot_gacha",
            Self::Album => "reddot_album",
            Self::Avatar => "reddot_avatar",
            Self::Frame => "reddot_frame",
            Self::Card => "reddot_card",
            Self::Title => "reddot_title",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "reddot_" => Some(Self::Reddot),
            "reddot_item" => Some(Self::Item),
            "reddot_port" => Some(Self::Port),
            "reddot_feat" => Some(Self::Feat),
            "reddot_rolefile" => Some(Self::Rolefile),
            "reddot_partner" => Some(Self::Partner),
            "reddot_equip" => Some(Self::Equip),
            "reddot_stone" => Some(Self::Stone),
            "reddot_archive" => Some(Self::Archive),
            "reddot_gacha" => Some(Self::Gacha),
            "reddot_album" => Some(Self::Album),
            "reddot_avatar" => Some(Self::Avatar),
            "reddot_frame" => Some(Self::Frame),
            "reddot_card" => Some(Self::Card),
            "reddot_title" => Some(Self::Title),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataItem {
    #[prost(int64, tag = "1")]
    pub user_item_id: i64,
    #[prost(int32, tag = "2")]
    pub item_id: i32,
    #[prost(int32, tag = "3")]
    pub amount: i32,
    #[prost(int32, tag = "4")]
    pub remain_sec: i32,
    #[prost(int32, tag = "5")]
    pub quality: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataUseItem {
    #[prost(int64, tag = "1")]
    pub user_item_id: i64,
    #[prost(int32, tag = "2")]
    pub item_id: i32,
    #[prost(int32, tag = "3")]
    pub amount: i32,
    #[prost(int32, tag = "4")]
    pub game_role_id: i32,
    #[prost(int64, tag = "5")]
    pub user_partner_id: i64,
    #[prost(int64, tag = "6")]
    pub team_equid_id: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataSkillStone {
    #[prost(int32, tag = "1")]
    pub pos: i32,
    #[prost(int64, tag = "2")]
    pub user_stone_id: i64,
    #[prost(bool, tag = "3")]
    pub locked: bool,
    #[prost(int32, tag = "4")]
    pub equiped_role: i32,
    #[prost(int32, tag = "5")]
    pub stone_id: i32,
    #[prost(int32, tag = "6")]
    pub quality: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataCollection {
    #[prost(int32, tag = "1")]
    pub cid: i32,
    #[prost(int64, tag = "2")]
    pub in_time: i64,
    #[prost(bool, tag = "3")]
    pub reward: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataPartner {
    #[prost(int32, tag = "1")]
    pub brek: i32,
    #[prost(int32, tag = "3")]
    pub exp: i32,
    #[prost(int32, tag = "8")]
    pub group_id: i32,
    #[prost(int64, tag = "9")]
    pub id: i64,
    #[prost(int32, tag = "10")]
    pub locked: i32,
    #[prost(int32, tag = "11")]
    pub lv: i32,
    #[prost(int32, tag = "12")]
    pub partner_id: i32,
    #[prost(int32, tag = "13")]
    pub quality: i32,
    #[prost(int32, tag = "14")]
    pub reson_lv: i32,
    #[prost(int32, tag = "15")]
    pub skill_lv: i32,
    #[prost(int64, tag = "16")]
    pub creat_at: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataStoneReward {
    #[prost(message, optional, tag = "1")]
    pub skillstone: ::core::option::Option<DcNetDataSkillStone>,
    #[prost(message, optional, tag = "2")]
    pub on_duplicate: ::core::option::Option<DcNetDataItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataRoleReward {
    #[prost(message, optional, tag = "1")]
    pub role_info: ::core::option::Option<DcNetDataRolesRolesDetail>,
    #[prost(message, optional, tag = "2")]
    pub on_duplicate: ::core::option::Option<DcNetDataItem>,
    #[prost(message, optional, tag = "3")]
    pub reward: ::core::option::Option<DcNetDataItem>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataPartnerReward {
    #[prost(message, optional, tag = "1")]
    pub partner: ::core::option::Option<DcNetDataPartner>,
    #[prost(message, optional, tag = "2")]
    pub reward: ::core::option::Option<DcNetDataItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataTakeRewardRes {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<DcNetDataItem>,
    #[prost(message, repeated, tag = "2")]
    pub equips: ::prost::alloc::vec::Vec<DcNetDataEquip>,
    #[prost(message, repeated, tag = "3")]
    pub stone_rewards: ::prost::alloc::vec::Vec<DcNetDataSkillStone>,
    #[prost(message, repeated, tag = "4")]
    pub role_rewards: ::prost::alloc::vec::Vec<DcNetDataRoleReward>,
    #[prost(message, repeated, tag = "5")]
    pub partner_rewards: ::prost::alloc::vec::Vec<DcNetDataPartnerReward>,
    #[prost(message, repeated, tag = "6")]
    pub collection_rewards: ::prost::alloc::vec::Vec<DcNetDataCollection>,
    #[prost(message, repeated, tag = "7")]
    pub teamequip_rewards: ::prost::alloc::vec::Vec<DcNetDataTeamEquip>,
    #[prost(message, repeated, tag = "8")]
    pub teamecore_rewards: ::prost::alloc::vec::Vec<DcNetDataTeamCore>,
    #[prost(int32, repeated, tag = "9")]
    pub skin_rewards: ::prost::alloc::vec::Vec<i32>,
    #[prost(message, repeated, tag = "10")]
    pub profileavatar_rewards: ::prost::alloc::vec::Vec<DcNetDataProfileAvatar>,
    #[prost(message, repeated, tag = "11")]
    pub profilecard_rewards: ::prost::alloc::vec::Vec<DcNetDataProfileCard>,
    #[prost(message, repeated, tag = "12")]
    pub profileframe_rewards: ::prost::alloc::vec::Vec<DcNetDataProfileFrame>,
    #[prost(message, repeated, tag = "13")]
    pub profiletitle_rewards: ::prost::alloc::vec::Vec<DcNetDataProfileTitle>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRewardsRes {
    #[prost(int64, tag = "1")]
    pub user_dat_id: i64,
    #[prost(int32, tag = "2")]
    pub reward: i32,
    #[prost(int32, tag = "3")]
    pub reward_type: i32,
    #[prost(int32, tag = "4")]
    pub amount: i32,
    #[prost(int32, tag = "5")]
    pub duplicate: i32,
    #[prost(int32, tag = "8")]
    pub quality: i32,
    #[prost(message, optional, tag = "9")]
    pub reward_ext: ::core::option::Option<DcNetDataItem>,
    #[prost(int32, tag = "10")]
    pub idx: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataGachaResInfo {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(bool, tag = "2")]
    pub hit_s: bool,
    #[prost(bool, tag = "3")]
    pub hit_10: bool,
    #[prost(int32, tag = "4")]
    pub r#type: i32,
    #[prost(int32, tag = "5")]
    pub time: i32,
    #[prost(int32, tag = "6")]
    pub gacha_id: i32,
    #[prost(int32, tag = "7")]
    pub reward_id: i32,
    #[prost(message, optional, tag = "8")]
    pub reward_res: ::core::option::Option<DcNetDataRewardsRes>,
    #[prost(int32, tag = "9")]
    pub extra_coin: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataGachaData {
    #[prost(int32, tag = "1")]
    pub gacha_id: i32,
    #[prost(int32, tag = "2")]
    pub remain_sec: i32,
    #[prost(int32, tag = "3")]
    pub gacha_count_10: i32,
    #[prost(int32, tag = "6")]
    pub reward10_id: i32,
    #[prost(int32, tag = "7")]
    pub gacha_type: i32,
    #[prost(int32, tag = "9")]
    pub min_10: i32,
    #[prost(int32, tag = "12")]
    pub all_count: i32,
    #[prost(int32, tag = "14")]
    pub reward_cnt: i32,
    #[prost(int32, tag = "15")]
    pub reward_num: i32,
    #[prost(bool, tag = "16")]
    pub taken_new_reward: bool,
    #[prost(message, repeated, tag = "17")]
    pub mall_goods: ::prost::alloc::vec::Vec<DcNetDataMallGoods>,
    #[prost(message, repeated, tag = "18")]
    pub buffers_items: ::prost::alloc::vec::Vec<DcNetDataGachaBufferItem>,
    #[prost(bool, tag = "19")]
    pub had_take_reward: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataEmail {
    #[prost(int64, tag = "1")]
    pub email_id: i64,
    #[prost(int32, tag = "2")]
    pub is_read: i32,
    #[prost(int32, tag = "3")]
    pub taken: i32,
    #[prost(int32, tag = "4")]
    pub sent_at: i32,
    #[prost(int32, tag = "5")]
    pub sender: i32,
    #[prost(string, tag = "6")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub content: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "8")]
    pub gift_list: ::prost::alloc::vec::Vec<DcNetDataReward>,
    #[prost(int32, tag = "9")]
    pub expire: i32,
    #[prost(int32, tag = "10")]
    pub sys_mail_id: i32,
    #[prost(string, tag = "11")]
    pub paramter: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataReward {
    #[prost(int32, tag = "1")]
    pub reward: i32,
    #[prost(int32, tag = "2")]
    pub reward_type: i32,
    #[prost(int32, tag = "3")]
    pub amount: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataEmailsIDs {
    #[prost(int64, repeated, tag = "1")]
    pub email_ids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataEquip {
    #[prost(int32, tag = "1")]
    pub equip_id: i32,
    #[prost(int32, tag = "2")]
    pub exp: i32,
    #[prost(int64, tag = "3")]
    pub user_equip_id: i64,
    #[prost(int32, tag = "4")]
    pub in_group: i32,
    #[prost(int32, tag = "5")]
    pub locked: i32,
    #[prost(int32, tag = "6")]
    pub level: i32,
    #[prost(int32, tag = "7")]
    pub equiped_role: i32,
    #[prost(int32, tag = "8")]
    pub pos: i32,
    #[prost(int32, tag = "9")]
    pub main_words_id: i32,
    #[prost(int32, repeated, tag = "10")]
    pub deputy_words_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, tag = "11")]
    pub quality: i32,
    #[prost(int32, repeated, tag = "12")]
    pub random_words_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, tag = "13")]
    pub minnum: i32,
    #[prost(int32, tag = "14")]
    pub tmp_word: i32,
    #[prost(int32, tag = "15")]
    pub tmp_word_idx: i32,
    #[prost(int64, tag = "16")]
    pub creat_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataEquipsGroup {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int32, tag = "2")]
    pub game_role_id: i32,
    #[prost(string, tag = "3")]
    pub group_name: ::prost::alloc::string::String,
    #[prost(int64, repeated, tag = "4")]
    pub user_equip_ids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataEquipSetRes {
    #[prost(message, optional, tag = "1")]
    pub equip_info: ::core::option::Option<DcNetDataEquip>,
    #[prost(message, repeated, tag = "2")]
    pub dropped_list: ::prost::alloc::vec::Vec<DcNetDataEquip>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataEquipsLock {
    #[prost(int32, tag = "1")]
    pub do_lock: i32,
    #[prost(int64, tag = "2")]
    pub user_equip_id: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataEquipGroupId {
    #[prost(int64, tag = "1")]
    pub id: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataFormationPos {
    #[prost(int32, tag = "2")]
    pub game_role_id: i32,
    #[prost(int32, tag = "3")]
    pub key_num: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataFormation {
    #[prost(int32, tag = "1")]
    pub formation_id: i32,
    #[prost(string, tag = "4")]
    pub remark: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub poss: ::prost::alloc::vec::Vec<DcNetDataFormationPos>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataMissonInfo {
    #[prost(int32, tag = "1")]
    pub misson_id: i32,
    #[prost(int32, tag = "2")]
    pub total_num: i32,
    #[prost(int32, tag = "3")]
    pub curr_num: i32,
    #[prost(bool, tag = "4")]
    pub taken: bool,
    #[prost(int32, tag = "5")]
    pub take_time: i32,
    #[prost(int32, tag = "6")]
    pub r#type: i32,
    #[prost(int32, tag = "7")]
    pub created_at: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataMonsterManual4Port {
    #[prost(uint32, repeated, tag = "1")]
    pub mons: ::prost::alloc::vec::Vec<u32>,
    #[prost(int32, tag = "2")]
    pub port_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRoleData {
    #[prost(int32, tag = "1")]
    pub game_role_id: i32,
    #[prost(int64, tag = "2")]
    pub damage: i64,
    #[prost(int64, tag = "3")]
    pub healing: i64,
    #[prost(int32, tag = "4")]
    pub death_count: i32,
    #[prost(int32, tag = "5")]
    pub max_comb: i32,
    #[prost(int32, tag = "6")]
    pub monster_killed: i32,
    #[prost(int32, tag = "7")]
    pub hp_remain: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataMonsterKilledInfo {
    #[prost(uint32, tag = "1")]
    pub enemy_hash: u32,
    #[prost(int32, tag = "2")]
    pub amount: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataParamsSettlement {
    #[prost(int32, tag = "1")]
    pub max_comb: i32,
    #[prost(int32, tag = "2")]
    pub all_death_count: i32,
    #[prost(int32, tag = "3")]
    pub id: i32,
    #[prost(int32, tag = "4")]
    pub time_sec: i32,
    #[prost(int32, tag = "5")]
    pub is_completed: i32,
    #[prost(message, repeated, tag = "6")]
    pub role_data: ::prost::alloc::vec::Vec<DcNetDataRoleData>,
    #[prost(message, repeated, tag = "7")]
    pub monsters: ::prost::alloc::vec::Vec<DcNetDataMonsterKilledInfo>,
    #[prost(int32, tag = "8")]
    pub boss_hp_remain: i32,
    #[prost(bool, repeated, tag = "9")]
    pub stars: ::prost::alloc::vec::Vec<bool>,
    #[prost(string, tag = "10")]
    pub boss_monster_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "11")]
    pub reward_list: ::prost::alloc::vec::Vec<DcNetDataReward>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataPort {
    #[prost(int32, tag = "1")]
    pub pass_cnt: i32,
    #[prost(bool, tag = "2")]
    pub is_c: bool,
    #[prost(bool, tag = "3")]
    pub is_f: bool,
    #[prost(int32, tag = "4")]
    pub port_id: i32,
    #[prost(int32, tag = "5")]
    pub s1: i32,
    #[prost(int32, tag = "6")]
    pub s2: i32,
    #[prost(int32, tag = "7")]
    pub s3: i32,
    #[prost(int32, tag = "8")]
    pub t_cnt: i32,
    #[prost(int32, tag = "9")]
    pub updated_at: i32,
    #[prost(int32, tag = "10")]
    pub id: i32,
    #[prost(int32, tag = "11")]
    pub all_cnt: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataAttrUpData {
    #[prost(int32, tag = "1")]
    pub attr_lv: i32,
    #[prost(int32, tag = "2")]
    pub attr_exp: i32,
    #[prost(int32, tag = "3")]
    pub add_exp: i32,
    #[prost(message, repeated, tag = "4")]
    pub items: ::prost::alloc::vec::Vec<DcNetDataItem>,
    #[prost(bool, tag = "5")]
    pub is_lv_up: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoleInfo {
    #[prost(int32, tag = "1")]
    pub role_id: i32,
    #[prost(message, optional, tag = "2")]
    pub lv_up_data: ::core::option::Option<DcNetDataAttrUpData>,
    #[prost(message, optional, tag = "3")]
    pub fetter_up_data: ::core::option::Option<DcNetDataAttrUpData>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRoleBasicInfo {
    #[prost(int32, tag = "1")]
    pub game_role_id: i32,
    #[prost(int32, tag = "2")]
    pub level: i32,
    #[prost(int32, tag = "3")]
    pub qua: i32,
    #[prost(int32, tag = "4")]
    pub brek_pos: i32,
    #[prost(int32, tag = "5")]
    pub position: i32,
    #[prost(int32, tag = "6")]
    pub maid_qua: i32,
    #[prost(int32, tag = "8")]
    pub exp: i32,
    #[prost(int32, tag = "12")]
    pub element: i32,
    #[prost(int32, tag = "13")]
    pub appear_skill_key: i32,
    #[prost(int64, tag = "14")]
    pub user_partner_id: i64,
    #[prost(int32, tag = "15")]
    pub created_at: i32,
    #[prost(int32, tag = "16")]
    pub element4call: i32,
    #[prost(int32, tag = "17")]
    pub skin_id: i32,
    #[prost(int64, tag = "18")]
    pub user_role_id: i64,
    #[prost(bool, tag = "19")]
    pub cur_mc: bool,
    #[prost(int32, repeated, tag = "20")]
    pub awards: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRolesBrekPoint {
    #[prost(int32, tag = "1")]
    pub lv: i32,
    #[prost(int32, tag = "2")]
    pub pos: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataSkill {
    #[prost(int32, tag = "1")]
    pub lv: i32,
    #[prost(string, tag = "2")]
    pub skill_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub eff_list: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "4")]
    pub disabled: bool,
    #[prost(uint32, tag = "5")]
    pub hash: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataRolesRolesDetail {
    #[prost(message, optional, tag = "1")]
    pub role_basic_info: ::core::option::Option<DcNetDataRoleBasicInfo>,
    #[prost(message, repeated, tag = "2")]
    pub brek_points: ::prost::alloc::vec::Vec<DcNetDataRolesBrekPoint>,
    #[prost(message, repeated, tag = "3")]
    pub equips: ::prost::alloc::vec::Vec<DcNetDataEquip>,
    #[prost(message, repeated, tag = "4")]
    pub talents: ::prost::alloc::vec::Vec<DcNetDataTalent>,
    #[prost(message, repeated, tag = "8")]
    pub skills: ::prost::alloc::vec::Vec<DcNetDataSkill>,
    #[prost(message, repeated, tag = "5")]
    pub skillstones: ::prost::alloc::vec::Vec<DcNetDataSkillStone>,
    #[prost(message, optional, tag = "6")]
    pub partner: ::core::option::Option<DcNetDataPartner>,
    #[prost(int32, tag = "7")]
    pub created_at: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRolesIdData {
    #[prost(int32, tag = "1")]
    pub game_role_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRolesChangeAppear {
    #[prost(int32, tag = "1")]
    pub game_role_id: i32,
    #[prost(int32, tag = "2")]
    pub key: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataSellRow {
    #[prost(int64, tag = "1")]
    pub user_dat_id: i64,
    #[prost(int32, tag = "2")]
    pub amount: i32,
    #[deprecated]
    #[prost(int32, tag = "3")]
    pub sell_type: i32,
    #[prost(int32, tag = "4")]
    pub index: i32,
    #[prost(int32, tag = "5")]
    pub item_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataPortsInfo {
    #[prost(message, repeated, tag = "1")]
    pub ports: ::prost::alloc::vec::Vec<DcNetDataPort>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataShop {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub remain_sec: i32,
    #[prost(int32, tag = "3")]
    pub goods_num: i32,
    #[prost(int32, tag = "4")]
    pub shop_type: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataShopShip {
    #[prost(int32, tag = "1")]
    pub refresh_times: i32,
    #[prost(int32, repeated, tag = "2")]
    pub tag_packed: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, tag = "3")]
    pub tags: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, tag = "4")]
    pub remain_sec: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataShopGoods {
    #[prost(int32, tag = "1")]
    pub goods_id: i32,
    #[prost(int32, tag = "2")]
    pub shop_id: i32,
    #[prost(int32, tag = "3")]
    pub buy_limit: i32,
    #[prost(int32, tag = "4")]
    pub bought: i32,
    #[prost(string, tag = "5")]
    pub goods: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub price: ::prost::alloc::string::String,
    #[prost(int32, tag = "7")]
    pub remain_sec: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DcNetDataRankElem {
    #[prost(uint32, tag = "1")]
    pub rank: u32,
    #[prost(double, tag = "2")]
    pub score: f64,
    #[prost(int64, tag = "3")]
    pub uid: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DcNetDataBossInfo {
    #[prost(int32, tag = "1")]
    pub stage_id: i32,
    #[prost(double, tag = "2")]
    pub score: f64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataAssistRole {
    #[prost(int32, tag = "1")]
    pub role_id: i32,
    #[prost(int32, tag = "2")]
    pub level: i32,
    #[prost(int32, tag = "3")]
    pub key_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataFriendInfo {
    #[prost(int64, tag = "1")]
    pub uid: i64,
    #[prost(int32, tag = "2")]
    pub level: i32,
    #[prost(int64, tag = "3")]
    pub last_login_time: i64,
    #[prost(message, repeated, tag = "4")]
    pub roles: ::prost::alloc::vec::Vec<DcNetDataAssistRole>,
    #[prost(bool, tag = "5")]
    pub send_point: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataGachaLog {
    #[prost(int32, tag = "1")]
    pub time: i32,
    #[prost(int32, tag = "2")]
    pub reward: i32,
    #[prost(int32, tag = "3")]
    pub gacha_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataGachaSelect {
    #[prost(int32, tag = "1")]
    pub gacha_id: i32,
    #[prost(int32, tag = "2")]
    pub rid: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataGachaBufferItem {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub gacha_id: i32,
    #[prost(int32, tag = "3")]
    pub rid: i32,
    #[prost(int32, tag = "4")]
    pub amount: i32,
    #[prost(int32, tag = "5")]
    pub unit: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataTaskStatus {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(enumeration = "TaskStatus", tag = "2")]
    pub status: i32,
    #[prost(int64, tag = "3")]
    pub picked_at: i64,
    #[prost(int32, tag = "4")]
    pub progress: i32,
    #[prost(int32, tag = "5")]
    pub total: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataTaskGroupStatus {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(enumeration = "TaskStatus", tag = "2")]
    pub status: i32,
    #[prost(message, optional, tag = "3")]
    pub curr_task: ::core::option::Option<DcNetDataTaskStatus>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataTaskChanged {
    #[prost(message, repeated, tag = "1")]
    pub tasklist: ::prost::alloc::vec::Vec<DcNetDataTaskStatus>,
    #[prost(message, optional, tag = "2")]
    pub rewards: ::core::option::Option<DcNetDataTakeRewardRes>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataInteractObj {
    #[prost(string, tag = "1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub interactive: bool,
    #[prost(int32, tag = "3")]
    pub status: i32,
    #[prost(int32, tag = "4")]
    pub count: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataTBoxInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub status: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRBoxInfo {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub r#type: i32,
    #[prost(int32, tag = "3")]
    pub point_id: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataTpMapInfo {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataUnlockSKill {
    #[prost(int32, tag = "1")]
    pub game_role_id: i32,
    #[prost(string, repeated, tag = "2")]
    pub skill_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataMonsterDrop {
    #[prost(string, tag = "1")]
    pub monster_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub monster_num: i32,
    #[prost(message, repeated, tag = "3")]
    pub reward_list: ::prost::alloc::vec::Vec<DcNetDataReward>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataAlbums {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(enumeration = "AlbumStatus", tag = "2")]
    pub status: i32,
    #[prost(int32, tag = "3")]
    pub sort: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataLocal {
    #[prost(int32, tag = "1")]
    pub region: i32,
    #[prost(string, tag = "2")]
    pub local: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub local2: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataWarnMonster {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub game_play_id: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataSms {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(bool, tag = "2")]
    pub read: bool,
    #[prost(int32, repeated, tag = "3")]
    pub selected: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataFavor {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub exp: i32,
    #[prost(int32, tag = "3")]
    pub lv: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataRegion {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub remain_sec: i32,
    #[prost(message, repeated, tag = "4")]
    pub tasks: ::prost::alloc::vec::Vec<DcNetDataTaskGroupStatus>,
    #[prost(int32, tag = "5")]
    pub level: i32,
    #[prost(message, optional, tag = "6")]
    pub region_coin: ::core::option::Option<DcNetDataRegionCoinLimit>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataFeat {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(enumeration = "FeatStatus", tag = "2")]
    pub status: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataTrial {
    #[prost(int32, tag = "1")]
    pub trial_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataPhy {
    #[prost(message, optional, tag = "1")]
    pub item: ::core::option::Option<DcNetDataItem>,
    #[prost(int32, tag = "2")]
    pub cd_time: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataMallGoods {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub cd_time: i32,
    #[prost(int32, tag = "3")]
    pub bought: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataMall {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub cd_time: i32,
    #[prost(message, repeated, tag = "3")]
    pub goods: ::prost::alloc::vec::Vec<DcNetDataMallGoods>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataArchiveInfo {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub in_time: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataTaskCycle {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(bool, tag = "2")]
    pub taken: bool,
    #[prost(int32, tag = "3")]
    pub progress: i32,
    #[prost(int32, tag = "4")]
    pub total: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataAchi {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int64, tag = "2")]
    pub took_at: i64,
    #[prost(int32, tag = "3")]
    pub progress: i32,
    #[prost(int32, tag = "4")]
    pub total: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataCheckInfo {
    #[prost(int32, tag = "1")]
    pub check_days: i32,
    #[prost(int32, repeated, tag = "2")]
    pub has_get_days: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, tag = "3")]
    pub cur_aid: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataActivityOpenInfo {
    #[prost(int32, tag = "1")]
    pub aid: i32,
    #[prost(int32, tag = "2")]
    pub remain_time: i32,
    #[prost(bool, tag = "3")]
    pub in_status: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataAct7Day {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int64, tag = "2")]
    pub took_at: i64,
    #[prost(int32, tag = "3")]
    pub progress: i32,
    #[prost(int32, tag = "4")]
    pub total: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataCollectionSuitReward {
    #[prost(int32, tag = "1")]
    pub sid: i32,
    #[prost(int32, repeated, tag = "2")]
    pub steps: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataCollectionPlaceInfo {
    #[prost(int32, tag = "1")]
    pub cid: i32,
    #[prost(int32, tag = "2")]
    pub pid: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataTalent {
    #[prost(int32, tag = "1")]
    pub game_role_id: i32,
    #[prost(int32, tag = "2")]
    pub position: i32,
    #[prost(int32, tag = "3")]
    pub lv: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataActivityBossInfo {
    #[prost(int32, tag = "1")]
    pub g_id: i32,
    #[prost(int32, tag = "2")]
    pub damage: i32,
    #[prost(int32, repeated, tag = "3")]
    pub ids: ::prost::alloc::vec::Vec<i32>,
    #[prost(map = "int32, int32", tag = "4")]
    pub daily_rewards: ::std::collections::HashMap<i32, i32>,
    #[prost(int32, tag = "5")]
    pub daily_damage: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataBossRankElem {
    #[prost(uint32, tag = "1")]
    pub rank: u32,
    #[prost(double, tag = "2")]
    pub score: f64,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, repeated, tag = "4")]
    pub rids: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataActivityChallenge {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(bool, tag = "2")]
    pub enabled: bool,
    #[prost(message, optional, tag = "3")]
    pub challenge_info: ::core::option::Option<DcNetDataChallenge>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataChallenge {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub stars: i32,
    #[prost(bool, tag = "3")]
    pub finished: bool,
    #[prost(bool, tag = "4")]
    pub claimed: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataRouge {
    #[prost(message, optional, tag = "1")]
    pub info: ::core::option::Option<DcNetDataRougeInfo>,
    #[prost(message, optional, tag = "2")]
    pub evt: ::core::option::Option<DcNetDataRougeEvent>,
    #[prost(message, optional, tag = "3")]
    pub subevt: ::core::option::Option<DcNetDataRougeSubEvt>,
    #[prost(message, optional, tag = "4")]
    pub next: ::core::option::Option<DcNetDataRougeNext>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataRougeInfo {
    #[prost(int32, tag = "1")]
    pub rouge_id: i32,
    #[prost(int32, tag = "2")]
    pub node_group_id: i32,
    #[prost(int32, tag = "3")]
    pub node_id: i32,
    #[prost(int32, tag = "4")]
    pub game_play_id: i32,
    #[prost(int32, tag = "5")]
    pub pressure: i32,
    #[prost(int32, tag = "6")]
    pub coin: i32,
    #[prost(int32, repeated, tag = "7")]
    pub buffs: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, tag = "8")]
    pub items: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, tag = "9")]
    pub bless_list: ::prost::alloc::vec::Vec<i32>,
    #[prost(message, repeated, tag = "10")]
    pub roles: ::prost::alloc::vec::Vec<DcNetDataRougeRole>,
    #[prost(int32, tag = "13")]
    pub event_pos: i32,
    #[prost(message, repeated, tag = "14")]
    pub eff_list: ::prost::alloc::vec::Vec<DcNetDataRougeEffect>,
    #[prost(int32, tag = "15")]
    pub first_buff_tag: i32,
    #[prost(map = "int32, int32", tag = "16")]
    pub init_roles: ::std::collections::HashMap<i32, i32>,
    #[prost(int32, tag = "17")]
    pub total_coin_spend: i32,
    #[prost(int32, tag = "18")]
    pub total_port_pass: i32,
    #[prost(int32, tag = "20")]
    pub total_boss_pass: i32,
    #[prost(int32, repeated, tag = "21")]
    pub tmp_buffs: ::prost::alloc::vec::Vec<i32>,
    #[prost(int64, repeated, tag = "22")]
    pub team_equips: ::prost::alloc::vec::Vec<i64>,
    #[prost(int32, tag = "23")]
    pub status: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRougeEffect {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(enumeration = "RougeEffect", tag = "2")]
    pub eff_id: i32,
    #[prost(string, tag = "3")]
    pub eff_params: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub remain_cnt: i32,
    #[prost(bool, tag = "5")]
    pub eternal: bool,
    #[prost(int32, tag = "6")]
    pub total_cnt: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRougeRole {
    #[prost(int32, tag = "1")]
    pub game_role_id: i32,
    #[prost(int32, tag = "2")]
    pub hp: i32,
    #[prost(int32, tag = "3")]
    pub ep: i32,
    #[prost(int32, tag = "4")]
    pub mp: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRougeNext {
    #[prost(int32, tag = "1")]
    pub node_group_id: i32,
    #[prost(int32, tag = "2")]
    pub node_id: i32,
    #[prost(enumeration = "RougeEvent", repeated, tag = "3")]
    pub events: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, tag = "4")]
    pub game_play_ids: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataRougeEvent {
    #[prost(enumeration = "RougeEvent", tag = "1")]
    pub event_id: i32,
    #[prost(int32, repeated, tag = "2")]
    pub buffs: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, tag = "3")]
    pub buff_times: i32,
    #[prost(int32, tag = "4")]
    pub buff_regen_times: i32,
    #[prost(int32, tag = "8")]
    pub trade_id: i32,
    #[prost(map = "int32, int32", tag = "9")]
    pub rand_goods: ::std::collections::HashMap<i32, i32>,
    #[prost(map = "int32, int32", tag = "10")]
    pub regular_goods: ::std::collections::HashMap<i32, i32>,
    #[prost(int32, tag = "11")]
    pub npc_id: i32,
    #[prost(message, repeated, tag = "12")]
    pub npc_effects: ::prost::alloc::vec::Vec<DcNetDataNpcEffect>,
    #[prost(int32, tag = "13")]
    pub coin: i32,
    #[prost(enumeration = "RougeEventStatus", tag = "14")]
    pub status: i32,
    #[prost(int32, tag = "16")]
    pub bless_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataNpcEffect {
    #[prost(int32, tag = "1")]
    pub eff_id: i32,
    #[prost(bool, tag = "2")]
    pub enabled: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataRougeSubEvt {
    #[prost(int32, tag = "1")]
    pub store_id: i32,
    #[prost(map = "int32, int32", tag = "2")]
    pub rand_goods: ::std::collections::HashMap<i32, i32>,
    #[prost(map = "int32, int32", tag = "3")]
    pub regular_goods: ::std::collections::HashMap<i32, i32>,
    #[prost(int32, tag = "4")]
    pub subevt_item_id: i32,
    #[prost(bool, tag = "5")]
    pub store_finished: bool,
    #[prost(bool, tag = "6")]
    pub item_finished: bool,
    #[prost(bool, tag = "7")]
    pub boss_box_opened: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRougeRow {
    #[prost(int32, tag = "1")]
    pub rouge_id: i32,
    #[prost(int32, tag = "2")]
    pub pass: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataTeamCore {
    #[prost(int32, tag = "1")]
    pub pos: i32,
    #[prost(int64, tag = "2")]
    pub id: i64,
    #[prost(bool, tag = "3")]
    pub locked: bool,
    #[prost(int64, tag = "4")]
    pub equiped_id: i64,
    #[prost(int32, tag = "5")]
    pub core_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataTeamEquip {
    #[prost(int32, tag = "1")]
    pub equiped_fid: i32,
    #[prost(int64, tag = "2")]
    pub id: i64,
    #[prost(bool, tag = "3")]
    pub locked: bool,
    #[prost(int32, tag = "4")]
    pub te_id: i32,
    #[prost(int32, tag = "5")]
    pub lv: i32,
    #[prost(int32, tag = "6")]
    pub exp: i32,
    #[prost(int32, tag = "7")]
    pub main_words_id: i32,
    #[prost(int32, tag = "8")]
    pub pos_num: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataTeamEquipDetail {
    #[prost(message, optional, tag = "1")]
    pub info: ::core::option::Option<DcNetDataTeamEquip>,
    #[prost(map = "int32, int64", tag = "2")]
    pub core_info: ::std::collections::HashMap<i32, i64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataMoreChallengeInfo {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub cost_time: i32,
    #[prost(bool, tag = "3")]
    pub star1: bool,
    #[prost(bool, tag = "4")]
    pub star2: bool,
    #[prost(bool, tag = "5")]
    pub star3: bool,
    #[prost(int32, repeated, tag = "6")]
    pub received_rewards: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataMonsterPointGroup {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub points: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRoleAttrInfo {
    #[prost(int32, tag = "1")]
    pub role_id: i32,
    #[prost(int32, tag = "2")]
    pub mp: i32,
    #[prost(int32, tag = "3")]
    pub ep: i32,
    #[prost(int32, tag = "4")]
    pub hp: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataRecharge {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub price: i32,
    #[prost(map = "int32, int32", tag = "3")]
    pub goods: ::std::collections::HashMap<i32, i32>,
    #[prost(map = "int32, int32", tag = "4")]
    pub first_goods: ::std::collections::HashMap<i32, i32>,
    #[prost(map = "int32, int32", tag = "5")]
    pub other_goods: ::std::collections::HashMap<i32, i32>,
    #[prost(bool, tag = "6")]
    pub had_first_taken: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataMonthlyCard {
    #[prost(int64, tag = "1")]
    pub cd_sec: i64,
    #[prost(int64, tag = "2")]
    pub bought_time: i64,
    #[prost(int64, tag = "3")]
    pub expired_time: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataDungeonSweepInfo {
    #[prost(message, optional, tag = "1")]
    pub rewards: ::core::option::Option<DcNetDataTakeRewardRes>,
    #[prost(message, optional, tag = "2")]
    pub user_up_data: ::core::option::Option<DcNetDataAttrUpData>,
    #[prost(message, repeated, tag = "3")]
    pub favor_list: ::prost::alloc::vec::Vec<DcNetDataFavor>,
    #[prost(message, repeated, tag = "4")]
    pub roles: ::prost::alloc::vec::Vec<RoleInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataItemSelectReward {
    #[prost(int32, tag = "1")]
    pub rid: i32,
    #[prost(int32, tag = "2")]
    pub amount: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataBattlePass {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(enumeration = "PaidStatus", tag = "2")]
    pub paid_status: i32,
    #[prost(int32, tag = "3")]
    pub remain_sec: i32,
    #[prost(int32, tag = "4")]
    pub level: i32,
    #[prost(int32, tag = "5")]
    pub exp: i32,
    #[prost(map = "int32, int32", tag = "6")]
    pub taken: ::std::collections::HashMap<i32, i32>,
    #[prost(int32, tag = "7")]
    pub exp_week: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataBattlePassTask {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(enumeration = "TaskStatus", tag = "2")]
    pub status: i32,
    #[prost(int32, tag = "3")]
    pub progress: i32,
    #[prost(int32, tag = "4")]
    pub total: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataBossRushInfo {
    #[prost(message, repeated, tag = "1")]
    pub boss_base: ::prost::alloc::vec::Vec<DcNetDataBossRushBase>,
    #[prost(int32, repeated, tag = "2")]
    pub ids: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, tag = "3")]
    pub curr_bid: i32,
    #[prost(int32, tag = "4")]
    pub last_bid: i32,
    #[prost(int64, tag = "5")]
    pub max_damage: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataBossRushBase {
    #[prost(int32, tag = "1")]
    pub pid: i32,
    #[prost(int32, repeated, tag = "2")]
    pub role_ids: ::prost::alloc::vec::Vec<i32>,
    #[prost(int64, tag = "3")]
    pub damage: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataBossRushRankElem {
    #[prost(uint32, tag = "1")]
    pub rank: u32,
    #[prost(double, tag = "2")]
    pub score: f64,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub rids: ::prost::alloc::vec::Vec<DcNetDataBossRushBase>,
    #[prost(int32, tag = "5")]
    pub avatar: i32,
    #[prost(int32, tag = "6")]
    pub avatar_frame: i32,
    #[prost(int32, tag = "7")]
    pub title: i32,
    #[prost(int64, tag = "8")]
    pub uid: i64,
    #[prost(int32, tag = "9")]
    pub level: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRift {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub battle_remain_sec: i32,
    #[prost(int32, tag = "3")]
    pub rest_remain_sec: i32,
    #[prost(message, optional, tag = "4")]
    pub rift_initail_item: ::core::option::Option<DcNetDataItem>,
    #[prost(message, optional, tag = "5")]
    pub daily_took_item: ::core::option::Option<DcNetDataItem>,
    #[prost(int64, tag = "6")]
    pub battle_end_time: i64,
    #[prost(int64, tag = "7")]
    pub rest_end_time: i64,
    #[prost(int64, tag = "8")]
    pub best_buff_score: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRiftRank {
    #[prost(int32, tag = "1")]
    pub score: i32,
    #[prost(int32, tag = "2")]
    pub rank: i32,
    #[prost(string, tag = "3")]
    pub nickname: ::prost::alloc::string::String,
    #[prost(int32, repeated, tag = "4")]
    pub roles: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, tag = "5")]
    pub avatar: i32,
    #[prost(int32, tag = "6")]
    pub avatar_frame: i32,
    #[prost(int32, tag = "7")]
    pub title: i32,
    #[prost(int64, tag = "8")]
    pub uid: i64,
    #[prost(int64, tag = "9")]
    pub buff_score: i64,
    #[prost(int32, tag = "10")]
    pub level: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataRiftTask {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub progress: i32,
    #[prost(int32, tag = "3")]
    pub total: i32,
    #[prost(bool, tag = "4")]
    pub took: bool,
    #[prost(map = "int32, int32", tag = "5")]
    pub reward: ::std::collections::HashMap<i32, i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataRegionCoinLimit {
    #[prost(int32, tag = "1")]
    pub coin_id: i32,
    #[prost(int32, tag = "2")]
    pub num: i32,
    #[prost(int32, tag = "3")]
    pub limit: i32,
    #[prost(bool, tag = "4")]
    pub reach_limit: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataProfileFrame {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int64, tag = "2")]
    pub end_time: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataProfileTitle {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int64, tag = "2")]
    pub end_time: i64,
    #[prost(int32, tag = "3")]
    pub num: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataProfileCard {
    #[prost(int32, tag = "1")]
    pub id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataProfileAvatar {
    #[prost(int32, tag = "1")]
    pub id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataSocialUserProfile {
    #[prost(int64, tag = "1")]
    pub uid: i64,
    #[prost(string, tag = "2")]
    pub nickname: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub avatar: i32,
    #[prost(int32, tag = "4")]
    pub avatar_frame: i32,
    #[prost(int32, tag = "5")]
    pub card: i32,
    #[prost(int32, tag = "6")]
    pub title: i32,
    #[prost(int32, tag = "7")]
    pub level: i32,
    #[prost(int32, tag = "8")]
    pub world_lv: i32,
    #[prost(int32, tag = "9")]
    pub chest_num: i32,
    #[prost(string, tag = "10")]
    pub roles: ::prost::alloc::string::String,
    #[prost(map = "string, int32", tag = "11")]
    pub archs: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    #[prost(string, tag = "12")]
    pub gs: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub online_time: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub offline_time: ::prost::alloc::string::String,
    #[prost(int32, tag = "15")]
    pub util_last_login_sec: i32,
    #[prost(int32, tag = "16")]
    pub gift: i32,
    #[prost(int32, tag = "17")]
    pub gift_sent: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DcNetDataFriendsInfo {
    #[prost(message, repeated, tag = "1")]
    pub friends: ::prost::alloc::vec::Vec<DcNetDataSocialUserProfile>,
    #[prost(message, repeated, tag = "2")]
    pub pending_approves: ::prost::alloc::vec::Vec<DcNetDataSocialUserProfile>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataVersionChallengeInfo {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(bool, tag = "2")]
    pub star1: bool,
    #[prost(bool, tag = "3")]
    pub star2: bool,
    #[prost(bool, tag = "4")]
    pub star3: bool,
    #[prost(int32, repeated, tag = "5")]
    pub received_rewards: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataVersionChallengeStage {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub countdown: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataVersionTask {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(enumeration = "TaskStatus", tag = "2")]
    pub status: i32,
    #[prost(int32, tag = "3")]
    pub progress: i32,
    #[prost(int32, tag = "4")]
    pub total: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DcNetDataMoreTeamGroup {
    #[prost(int32, tag = "1")]
    pub gid: i32,
    #[prost(int32, tag = "2")]
    pub countdown: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TaskStatus {
    Disabled = 0,
    Picked = 2,
    Done = 3,
    Discard = 4,
}
impl TaskStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Disabled => "disabled",
            Self::Picked => "picked",
            Self::Done => "done",
            Self::Discard => "discard",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "disabled" => Some(Self::Disabled),
            "picked" => Some(Self::Picked),
            "done" => Some(Self::Done),
            "discard" => Some(Self::Discard),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AlbumStatus {
    AlbumUnknown = 0,
    Unlocked = 1,
    Selected = 2,
}
impl AlbumStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::AlbumUnknown => "album_unknown",
            Self::Unlocked => "unlocked",
            Self::Selected => "selected",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "album_unknown" => Some(Self::AlbumUnknown),
            "unlocked" => Some(Self::Unlocked),
            "selected" => Some(Self::Selected),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FeatStatus {
    FeatLocked = 0,
    FeatUnlocked = 1,
    FeatUnlockable = 2,
}
impl FeatStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::FeatLocked => "feat_locked",
            Self::FeatUnlocked => "feat_unlocked",
            Self::FeatUnlockable => "feat_unlockable",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "feat_locked" => Some(Self::FeatLocked),
            "feat_unlocked" => Some(Self::FeatUnlocked),
            "feat_unlockable" => Some(Self::FeatUnlockable),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RougeEvent {
    Re = 0,
    ReBuff = 1,
    ReTrade = 2,
    ReNpc = 3,
    ReCoinbox = 4,
    ReRest = 5,
    ReBlessing = 6,
}
impl RougeEvent {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Re => "re_",
            Self::ReBuff => "re_buff",
            Self::ReTrade => "re_trade",
            Self::ReNpc => "re_npc",
            Self::ReCoinbox => "re_coinbox",
            Self::ReRest => "re_rest",
            Self::ReBlessing => "re_blessing",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "re_" => Some(Self::Re),
            "re_buff" => Some(Self::ReBuff),
            "re_trade" => Some(Self::ReTrade),
            "re_npc" => Some(Self::ReNpc),
            "re_coinbox" => Some(Self::ReCoinbox),
            "re_rest" => Some(Self::ReRest),
            "re_blessing" => Some(Self::ReBlessing),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RougeEffect {
    Eff = 0,
    EffPressureAdd = 1,
    EffHpAddRate = 2,
    EffHpAddValue = 3,
    EffCoinAddRate = 4,
    EffCoinAddValue = 5,
    EffBuffAdd = 6,
    EffRougeBuffAdd = 7,
    EffRougeBuff4monster = 8,
    EffEnterBattle = 9,
    EffPressureAddRate = 10,
    EffCoinGain = 11,
    EffAllPressureGain = 12,
    EffBattleCoinGain = 13,
    EffBattlePressureGain = 14,
    EffInitialBuff = 15,
    EffInitialItem = 16,
    EffInitialCoin = 17,
    EffInitialBlessing = 18,
    EffBuffRand = 19,
    EffBuffTagRand = 20,
    EffRestChange = 21,
    EffRougeBuffCount = 22,
    EffTradeDiscount = 23,
    EffBattleHpRecover = 24,
    EffHpLimitAddRate = 25,
}
impl RougeEffect {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Eff => "eff_",
            Self::EffPressureAdd => "eff_pressure_add",
            Self::EffHpAddRate => "eff_hp_add_rate",
            Self::EffHpAddValue => "eff_hp_add_value",
            Self::EffCoinAddRate => "eff_coin_add_rate",
            Self::EffCoinAddValue => "eff_coin_add_value",
            Self::EffBuffAdd => "eff_buff_add",
            Self::EffRougeBuffAdd => "eff_rouge_buff_add",
            Self::EffRougeBuff4monster => "eff_rouge_buff4monster",
            Self::EffEnterBattle => "eff_enter_battle",
            Self::EffPressureAddRate => "eff_pressure_add_rate",
            Self::EffCoinGain => "eff_coin_gain",
            Self::EffAllPressureGain => "eff_all_pressure_gain",
            Self::EffBattleCoinGain => "eff_battle_coin_gain",
            Self::EffBattlePressureGain => "eff_battle_pressure_gain",
            Self::EffInitialBuff => "eff_initial_buff",
            Self::EffInitialItem => "eff_initial_item",
            Self::EffInitialCoin => "eff_initial_coin",
            Self::EffInitialBlessing => "eff_initial_blessing",
            Self::EffBuffRand => "eff_buff_rand",
            Self::EffBuffTagRand => "eff_buff_tag_rand",
            Self::EffRestChange => "eff_rest_change",
            Self::EffRougeBuffCount => "eff_rouge_buff_count",
            Self::EffTradeDiscount => "eff_trade_discount",
            Self::EffBattleHpRecover => "eff_battle_hp_recover",
            Self::EffHpLimitAddRate => "eff_hp_limit_add_rate",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "eff_" => Some(Self::Eff),
            "eff_pressure_add" => Some(Self::EffPressureAdd),
            "eff_hp_add_rate" => Some(Self::EffHpAddRate),
            "eff_hp_add_value" => Some(Self::EffHpAddValue),
            "eff_coin_add_rate" => Some(Self::EffCoinAddRate),
            "eff_coin_add_value" => Some(Self::EffCoinAddValue),
            "eff_buff_add" => Some(Self::EffBuffAdd),
            "eff_rouge_buff_add" => Some(Self::EffRougeBuffAdd),
            "eff_rouge_buff4monster" => Some(Self::EffRougeBuff4monster),
            "eff_enter_battle" => Some(Self::EffEnterBattle),
            "eff_pressure_add_rate" => Some(Self::EffPressureAddRate),
            "eff_coin_gain" => Some(Self::EffCoinGain),
            "eff_all_pressure_gain" => Some(Self::EffAllPressureGain),
            "eff_battle_coin_gain" => Some(Self::EffBattleCoinGain),
            "eff_battle_pressure_gain" => Some(Self::EffBattlePressureGain),
            "eff_initial_buff" => Some(Self::EffInitialBuff),
            "eff_initial_item" => Some(Self::EffInitialItem),
            "eff_initial_coin" => Some(Self::EffInitialCoin),
            "eff_initial_blessing" => Some(Self::EffInitialBlessing),
            "eff_buff_rand" => Some(Self::EffBuffRand),
            "eff_buff_tag_rand" => Some(Self::EffBuffTagRand),
            "eff_rest_change" => Some(Self::EffRestChange),
            "eff_rouge_buff_count" => Some(Self::EffRougeBuffCount),
            "eff_trade_discount" => Some(Self::EffTradeDiscount),
            "eff_battle_hp_recover" => Some(Self::EffBattleHpRecover),
            "eff_hp_limit_add_rate" => Some(Self::EffHpLimitAddRate),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RougeEventStatus {
    Res = 0,
    ResBattleFinished = 1,
    ResFinished = 2,
}
impl RougeEventStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Res => "res_",
            Self::ResBattleFinished => "res_battle_finished",
            Self::ResFinished => "res_finished",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "res_" => Some(Self::Res),
            "res_battle_finished" => Some(Self::ResBattleFinished),
            "res_finished" => Some(Self::ResFinished),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PaidStatus {
    Free = 0,
    Advanced = 1,
    Premium = 2,
}
impl PaidStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Free => "Free",
            Self::Advanced => "Advanced",
            Self::Premium => "Premium",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Free" => Some(Self::Free),
            "Advanced" => Some(Self::Advanced),
            "Premium" => Some(Self::Premium),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SocialFriendOpt {
    Zero = 0,
    Request = 1,
    Approve = 2,
    Delete = 3,
    Gift = 4,
}
impl SocialFriendOpt {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Zero => "zero",
            Self::Request => "request",
            Self::Approve => "approve",
            Self::Delete => "delete",
            Self::Gift => "gift",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "zero" => Some(Self::Zero),
            "request" => Some(Self::Request),
            "approve" => Some(Self::Approve),
            "delete" => Some(Self::Delete),
            "gift" => Some(Self::Gift),
            _ => None,
        }
    }
}
