// This file is @generated by prost-build.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Id {
    NotifyNeverUsedZero = 0,
    DcNetWorkingCommonError = 9999,
    DcNetWorkingParamGmCmd = 9997,
    DcNetWorkingParamGachaDo = 1003,
    DcNetWorkingParamEmailsGetEmails = 1005,
    DcNetWorkingParamEmailsTakeGift = 1007,
    DcNetWorkingParamEmailsDelete = 1009,
    DcNetWorkingParamEmailsRead = 1011,
    DcNetWorkingParamEquipsLevelUp = 1013,
    DcNetWorkingParamEquipsSet = 1015,
    DcNetWorkingParamEquipsUnset = 1017,
    DcNetWorkingParamEquipsLock = 1019,
    DcNetWorkingParamEquipsEquipSetGroup = 1021,
    DcNetWorkingParamEquipsEquipGetGroup = 1023,
    DcNetWorkingParamEquipsEquipDelGroup = 1025,
    DcNetWorkingParamEquipsSetEquips = 1027,
    DcNetWorkingParamFormationSet = 1029,
    DcNetWorkingParamItemsGet = 1031,
    DcNetWorkingParamItemsUseItem = 1033,
    DcNetWorkingParamMissonsList = 1035,
    DcNetWorkingParamMissonsTakeReward = 1037,
    DcNetWorkingParamMonstersMonsterManual4Port = 1041,
    DcNetWorkingParamNotice = 1043,
    DcNetWorkingParamPortsStart = 1045,
    DcNetWorkingParamReddotList = 1049,
    DcNetWorkingParamPortsSett = 1047,
    DcNetWorkingParamReddotCheck = 1051,
    DcNetWorkingParamRolesUserRoles = 1053,
    DcNetWorkingParamRolesRankUp = 1055,
    DcNetWorkingParamRolesBrekUp = 1057,
    DcNetWorkingParamRolesLevelUp = 1059,
    DcNetWorkingParamRolesGetFetterRewards = 1061,
    DcNetWorkingParamRolesTakeFetterReward = 1063,
    DcNetWorkingParamRolesChangeAppear = 1065,
    DcNetWorkingParamRolesChangeElement = 1069,
    DcNetWorkingParamShopSell = 1071,
    DcNetWorkingParamSkillsGetInfo = 1073,
    DcNetWorkingParamSkillsLevelUp = 1075,
    DcNetWorkingParamSkillstonesSet = 1081,
    DcNetWorkingParamSkillstonesUnset = 1083,
    DcNetWorkingParamSkillstonesLock = 1085,
    DcNetWorkingParamPartnerLvUp = 1087,
    DcNetWorkingParamPartnerChange = 1089,
    DcNetWorkingParamPartnerLock = 1091,
    DcNetWorkingParamPartnerImpress = 1093,
    DcNetWorkingParamPartnerBrek = 1097,
    DcNetWorkingParamUserGetInfo = 1099,
    DcNetWorkingParamUserGetPhyInfo = 1101,
    DcNetWorkingParamShopGetInfo = 1103,
    DcNetWorkingParamShopSetShipTags = 1105,
    DcNetWorkingParamShopShipTagRefresh = 1107,
    DcNetWorkingParamShopGetGoods = 1109,
    DcNetWorkingParamShopBuy = 1111,
    DcNetWorkingParamGachaGetList = 1115,
    DcNetWorkingParamRolesProfile = 1117,
    DcNetWorkingParamEquipsList = 1125,
    DcNetWorkingParamSkillStoneList = 1127,
    DcNetWorkingParamPartnerList = 1129,
    DcNetWorkingParamFormationList = 1131,
    DcNetWorkingParamFeatList = 1133,
    DcNetWorkingParamPortList = 1135,
    DcNetWorkingParamCheckinInfo = 1141,
    DcNetWorkingParamCheckinReward = 1143,
    DcNetWorkingParamRolesChangeElement4Call = 1145,
    DcNetWorkingParamUserGuideSave = 1171,
    DcNetWorkingParamUserGuideList = 1173,
    DcNetWorkingParamGachaLogs = 1181,
    DcNetWorkingParamNaming = 1187,
    DcNetWorkingParamSysInfo = 1189,
    DcNetWorkingParamRoleSkinGetList = 1191,
    DcNetWorkingParamRolesChangeSkin = 1193,
    DcNetWorkingParamExchangePhy = 1195,
    DcNetWorkingParamExchangeInfo = 1197,
    DcNetWorkingParamUserChangeBannerGril = 1199,
    DcNetWorkingParamSkillResetLv = 1201,
    DcNetWorkingParamCheckinCheck = 1203,
    DcNetWorkingParamTaskList = 1205,
    DcNetWorkingParamTask2Done = 1207,
    DcNetWorkingParamInteractObjs = 1211,
    DcNetWorkingParamInteracting = 1213,
    DcNetWorkingParamTBoxInfoList = 1215,
    DcNetWorkingParamTBoxTakeReward = 1217,
    DcNetWorkingParamRBoxInfoList = 1219,
    DcNetWorkingParamRBoxTakeReward = 1221,
    DcNetWorkingParamTpMapInfoList = 1223,
    DcNetWorkingParamTpMapSet = 1225,
    DcNetWorkingParamDenseFogList = 1227,
    DcNetWorkingParamDenseFogSet = 1229,
    DcNetWorkingParamPlayingPortSet = 1231,
    DcNetWorkingParamPlayingPortGet = 1233,
    DcNetWorkingParamFormationCurSet = 1235,
    DcNetWorkingParamFormationAdd = 1237,
    DcNetWorkingParamFormationDel = 1239,
    DcNetWorkingParamPartnerUnset = 1241,
    DcNetWorkingParamDungeonStart = 1243,
    DcNetWorkingParamDungeonSett = 1245,
    DcNetWorkingParamEquipsSwap = 1247,
    DcNetWorkingParamPartnerSwap = 1249,
    DcNetWorkingParamAlbumsList = 1251,
    DcNetWorkingParamAlbumsSelect = 1253,
    DcNetWorkingParamLocalList = 1255,
    DcNetWorkingParamLocalSet = 1257,
    DcNetWorkingParamTrialSave = 1259,
    DcNetWorkingParamTrialDone = 1261,
    DcNetWorkingParamTrialInfo = 1263,
    DcNetWorkingParamSmsList = 1271,
    DcNetWorkingParamSmsRead = 1273,
    DcNetWorkingParamFavorList = 1275,
    DcNetWorkingParamRegionInfo = 1277,
    DcNetWorkingParamRegionTakeDailyReward = 1279,
    DcNetWorkingParamRegionTakeTask = 1281,
    DcNetWorkingParamRolesMcSwitch = 1283,
    DcNetWorkingParamTaskGoalSet = 1285,
    DcNetWorkingParamRegionList = 1287,
    DcNetWorkingParamFeatUnlock = 1289,
    DcNetWorkingParamMallBuy = 1291,
    DcNetWorkingParamMallList = 1293,
    DcNetWorkingParamSkillstonesSwap = 1295,
    DcNetWorkingParamArchiveList = 1297,
    DcNetWorkingParamTrialList = 1299,
    DcNetWorkingParamTaskCycleList = 1301,
    DcNetWorkingParamTaskCycleTakeActivity = 1303,
    DcNetWorkingParamTaskCycleTakeReward = 1305,
    DcNetWorkingParamItemsConvert = 1307,
    DcNetWorkingParamItemsSynthesis = 1309,
    DcNetWorkingParamAchiList = 1311,
    DcNetWorkingParamAchiClaim = 1313,
    DcNetWorkingParamActivityOpenList = 1315,
    DcNetWorkingParamActivityLevelUpList = 1317,
    DcNetWorkingParamActivityLevelUpReward = 1319,
    DcNetWorkingParamActivity7DayList = 1321,
    DcNetWorkingParamActivity7DayClaim = 1323,
    DcNetWorkingParamActivity7DayPointClaim = 1325,
    DcNetWorkingParamCollectionList = 1327,
    DcNetWorkingParamCollectionReward = 1329,
    DcNetWorkingParamCollectionSuitRewardList = 1331,
    DcNetWorkingParamCollectionSuitReward = 1333,
    DcNetWorkingParamCollectionPlace = 1335,
    DcNetWorkingParamCollectionPlaceInfos = 1337,
    DcNetWorkingParamTalentLevelUp = 1339,
    DcNetWorkingParamCityGuideSet = 1341,
    DcNetWorkingParamCityGuideList = 1343,
    DcNetWorkingParamActivityBossChallengeSett = 1345,
    DcNetWorkingParamActivityBossChallengeInfo = 1347,
    DcNetWorkingParamActivityBossChallengeReward = 1349,
    DcNetWorkingParamActivityBossChallengeRank = 1351,
    DcNetWorkingParamActivityChallengesList = 1353,
    DcNetWorkingParamActivityChallengesClaim = 1355,
    DcNetWorkingParamChallengesReport = 1357,
    DcNetWorkingParamActivityChallengesPointClaim = 1359,
    DcNetWorkingParamChallengesParkourReport = 1361,
    DcNetWorkingParamChallengesList = 1363,
    DcNetWorkingParamFavorAdd = 1365,
    DcNetWorkingParamFavorUseItem = 1367,
    DcNetWorkingParamRougeStart = 1369,
    DcNetWorkingParamRougeNodeReport = 1371,
    DcNetWorkingParamRougeEnter = 1373,
    DcNetWorkingParamRougeBossBoxOpen = 1375,
    DcNetWorkingParamRougeNpcSelectEffect = 1377,
    DcNetWorkingParamRougeTradeBuy = 1379,
    DcNetWorkingParamRoleRankUpAward = 1381,
    DcNetWorkingParamRougeBuffSelect = 1383,
    DcNetWorkingParamRougeCoinboxOpen = 1385,
    DcNetWorkingParamRougeRest = 1387,
    DcNetWorkingParamRougeSubevtStoreBuy = 1389,
    DcNetWorkingParamRougeSubevtItem = 1391,
    DcNetWorkingParamRougeInfo = 1393,
    DcNetWorkingParamRougeFinish = 1395,
    DcNetWorkingParamRougeItemUse = 1397,
    DcNetWorkingParamActivityBossChallengeStart = 1399,
    DcNetWorkingParamTeamCoreList = 1401,
    DcNetWorkingParamTeamCoreCompose = 1403,
    DcNetWorkingParamTeamCoreLock = 1405,
    DcNetWorkingParamTeamEquipList = 1407,
    DcNetWorkingParamTeamEquipEquip = 1409,
    DcNetWorkingParamTeamEquipUnEquip = 1411,
    DcNetWorkingParamTeamEquipSetCore = 1413,
    DcNetWorkingParamTeamEquipUnSetCore = 1415,
    DcNetWorkingParamTeamEquipLock = 1417,
    DcNetWorkingParamTeamEquipLvUp = 1419,
    DcNetWorkingParamRougeBlessOpen = 1421,
    DcNetWorkingParamMoreTeamChallengeList = 1423,
    DcNetWorkingParamMoreTeamChallengeSett = 1425,
    DcNetWorkingParamMoreTeamChallengeAward = 1427,
    DcNetWorkingParamMoreTeamChallengeStart = 1429,
    DcNetWorkingParamRougeList = 1431,
    DcNetWorkingParamRougeWaiveBuff = 1433,
    DcNetWorkingParamRougeRegenBuff = 1435,
    DcNetWorkingParamRougeTechTree = 1437,
    DcNetWorkingParamRougeTechTake = 1439,
    DcNetWorkingParamRougeScoreRewardClaim = 1441,
    DcNetWorkingParamRougeFormSave = 1443,
    DcNetWorkingParamQuestionUrl = 1445,
    DcNetWorkingParamRougeStatusSet = 1457,
    DcNetWorkingParamMonsterPoints = 1459,
    DcNetWorkingParamMonsterPointHit = 1461,
    DcNetWorkingParamGachaClaimExtra = 1463,
    DcNetWorkingParamGoldCoinList = 1465,
    DcNetWorkingParamGoldCoinCollect = 1467,
    DcNetWorkingParamCollectionResList = 1469,
    DcNetWorkingParamCollectionResCollect = 1471,
    DcNetWorkingParamEquipsRandomWordRefresh = 1473,
    DcNetWorkingParamEquipsRandomWordReplace = 1475,
    DcNetWorkingParamGachaClaimCumReward = 1477,
    DcNetWorkingParamGachaBufferClaim = 1479,
    DcNetWorkingParamPartnerSkillUp = 1481,
    DcNetWorkingParamRoleAttrList = 1483,
    DcNetWorkingParamRoleAttrSave = 1485,
    DcNetWorkingParamRechargeList = 1491,
    DcNetWorkingParamDungeonList = 1493,
    DcNetWorkingParamDungeonSweep = 1495,
    DcNetWorkingParamExchangeSbs2hhs = 1497,
    DcNetWorkingParamItemSelectReward = 1499,
    DcNetWorkingParamActivityBossChallengeDailyReward = 1501,
    DcNetWorkingParamBattlePassInfo = 1503,
    DcNetWorkingParamBattlePassTasks = 1505,
    DcNetWorkingParamBattlePassTaskClaim = 1507,
    DcNetWorkingParamBattlePassClaim = 1509,
    DcNetWorkingParamBattlePassLevelUp = 1511,
    DcNetWorkingParamBossRushInfo = 1513,
    DcNetWorkingParamBossRushSett = 1515,
    DcNetWorkingParamBossRushReward = 1517,
    DcNetWorkingParamBossRushRank = 1519,
    DcNetWorkingParamRiftStart = 1521,
    DcNetWorkingParamRiftNext = 1523,
    DcNetWorkingParamRiftReport = 1525,
    DcNetWorkingParamRiftDefeat = 1527,
    DcNetWorkingParamRiftSettlment = 1529,
    DcNetWorkingParamRiftRank = 1531,
    DcNetWorkingParamRiftTask = 1533,
    DcNetWorkingParamRiftTaskClaim = 1535,
    DcNetWorkingParamRebateItemUse = 1537,
    DcNetWorkingParamRiftInfo = 1539,
    DcNetWorkingParamProfileList = 1541,
    DcNetWorkingParamProfileSet = 1543,
    DcNetWorkingParamFriendsInfo = 1545,
    DcNetWorkingParamFriendGiftSend = 1547,
    DcNetWorkingParamFriendGiftClaim = 1549,
    DcNetWorkingParamFriendsSearch = 1551,
    DcNetWorkingParamFriendsRequest = 1553,
    DcNetWorkingParamFriendsApprove = 1555,
    DcNetWorkingParamFriendsDelete = 1557,
    DcNetWorkingParamFriendsProfile = 1559,
    DcNetWorkingParamBossRushResetTeam = 1561,
    DcNetWorkingParamVersionChallengeStart = 1563,
    DcNetWorkingParamVersionChallengeList = 1565,
    DcNetWorkingParamVersionChallengeSett = 1567,
    DcNetWorkingParamVersionChallengeAward = 1569,
    DcNetWorkingParamVersionChallengeStageList = 1571,
    DcNetWorkingParamVersionTaskList = 1573,
    DcNetWorkingParamVersionTaskClaim = 1575,
    DcNetWorkingParamVersionActivityInfo = 1577,
    DcNetWorkingParamActivityLimitedLevelUpList = 1579,
    DcNetWorkingParamActivityLimitedLevelUpReward = 1581,
    DcNetWorkingParamMoreTeamChallengeGroupList = 1583,
}
impl Id {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NotifyNeverUsedZero => "NOTIFY_NEVER_USED_ZERO",
            Self::DcNetWorkingCommonError => "DCNetWorkingCommon_Error",
            Self::DcNetWorkingParamGmCmd => "DCNetWorkingParam_GM_Cmd",
            Self::DcNetWorkingParamGachaDo => "DCNetWorkingParam_Gacha_Do",
            Self::DcNetWorkingParamEmailsGetEmails => {
                "DCNetWorkingParam_Emails_GetEmails"
            }
            Self::DcNetWorkingParamEmailsTakeGift => "DCNetWorkingParam_Emails_TakeGift",
            Self::DcNetWorkingParamEmailsDelete => "DCNetWorkingParam_Emails_Delete",
            Self::DcNetWorkingParamEmailsRead => "DCNetWorkingParam_Emails_Read",
            Self::DcNetWorkingParamEquipsLevelUp => "DCNetWorkingParam_Equips_LevelUp",
            Self::DcNetWorkingParamEquipsSet => "DCNetWorkingParam_Equips_Set",
            Self::DcNetWorkingParamEquipsUnset => "DCNetWorkingParam_Equips_Unset",
            Self::DcNetWorkingParamEquipsLock => "DCNetWorkingParam_Equips_Lock",
            Self::DcNetWorkingParamEquipsEquipSetGroup => {
                "DCNetWorkingParam_Equips_EquipSetGroup"
            }
            Self::DcNetWorkingParamEquipsEquipGetGroup => {
                "DCNetWorkingParam_Equips_EquipGetGroup"
            }
            Self::DcNetWorkingParamEquipsEquipDelGroup => {
                "DCNetWorkingParam_Equips_EquipDelGroup"
            }
            Self::DcNetWorkingParamEquipsSetEquips => {
                "DCNetWorkingParam_Equips_SetEquips"
            }
            Self::DcNetWorkingParamFormationSet => "DCNetWorkingParam_Formation_Set",
            Self::DcNetWorkingParamItemsGet => "DCNetWorkingParam_Items_Get",
            Self::DcNetWorkingParamItemsUseItem => "DCNetWorkingParam_Items_UseItem",
            Self::DcNetWorkingParamMissonsList => "DCNetWorkingParam_Missons_List",
            Self::DcNetWorkingParamMissonsTakeReward => {
                "DCNetWorkingParam_Missons_TakeReward"
            }
            Self::DcNetWorkingParamMonstersMonsterManual4Port => {
                "DCNetWorkingParam_Monsters_MonsterManual4Port"
            }
            Self::DcNetWorkingParamNotice => "DCNetWorkingParam_Notice",
            Self::DcNetWorkingParamPortsStart => "DCNetWorkingParam_Ports_Start",
            Self::DcNetWorkingParamReddotList => "DCNetWorkingParam_Reddot_List",
            Self::DcNetWorkingParamPortsSett => "DCNetWorkingParam_Ports_Sett",
            Self::DcNetWorkingParamReddotCheck => "DCNetWorkingParam_Reddot_Check",
            Self::DcNetWorkingParamRolesUserRoles => "DCNetWorkingParam_Roles_UserRoles",
            Self::DcNetWorkingParamRolesRankUp => "DCNetWorkingParam_Roles_RankUp",
            Self::DcNetWorkingParamRolesBrekUp => "DCNetWorkingParam_Roles_BrekUp",
            Self::DcNetWorkingParamRolesLevelUp => "DCNetWorkingParam_Roles_LevelUp",
            Self::DcNetWorkingParamRolesGetFetterRewards => {
                "DCNetWorkingParam_Roles_GetFetterRewards"
            }
            Self::DcNetWorkingParamRolesTakeFetterReward => {
                "DCNetWorkingParam_Roles_TakeFetterReward"
            }
            Self::DcNetWorkingParamRolesChangeAppear => {
                "DCNetWorkingParam_Roles_ChangeAppear"
            }
            Self::DcNetWorkingParamRolesChangeElement => {
                "DCNetWorkingParam_Roles_ChangeElement"
            }
            Self::DcNetWorkingParamShopSell => "DCNetWorkingParam_Shop_Sell",
            Self::DcNetWorkingParamSkillsGetInfo => "DCNetWorkingParam_Skills_GetInfo",
            Self::DcNetWorkingParamSkillsLevelUp => "DCNetWorkingParam_Skills_LevelUp",
            Self::DcNetWorkingParamSkillstonesSet => "DCNetWorkingParam_Skillstones_Set",
            Self::DcNetWorkingParamSkillstonesUnset => {
                "DCNetWorkingParam_Skillstones_Unset"
            }
            Self::DcNetWorkingParamSkillstonesLock => {
                "DCNetWorkingParam_Skillstones_Lock"
            }
            Self::DcNetWorkingParamPartnerLvUp => "DCNetWorkingParam_Partner_LvUp",
            Self::DcNetWorkingParamPartnerChange => "DCNetWorkingParam_Partner_Change",
            Self::DcNetWorkingParamPartnerLock => "DCNetWorkingParam_Partner_Lock",
            Self::DcNetWorkingParamPartnerImpress => "DCNetWorkingParam_Partner_Impress",
            Self::DcNetWorkingParamPartnerBrek => "DCNetWorkingParam_Partner_Brek",
            Self::DcNetWorkingParamUserGetInfo => "DCNetWorkingParam_User_GetInfo",
            Self::DcNetWorkingParamUserGetPhyInfo => "DCNetWorkingParam_User_GetPhyInfo",
            Self::DcNetWorkingParamShopGetInfo => "DCNetWorkingParam_Shop_GetInfo",
            Self::DcNetWorkingParamShopSetShipTags => {
                "DCNetWorkingParam_Shop_SetShipTags"
            }
            Self::DcNetWorkingParamShopShipTagRefresh => {
                "DCNetWorkingParam_Shop_ShipTagRefresh"
            }
            Self::DcNetWorkingParamShopGetGoods => "DCNetWorkingParam_Shop_GetGoods",
            Self::DcNetWorkingParamShopBuy => "DCNetWorkingParam_Shop_Buy",
            Self::DcNetWorkingParamGachaGetList => "DCNetWorkingParam_Gacha_GetList",
            Self::DcNetWorkingParamRolesProfile => "DCNetWorkingParam_Roles_Profile",
            Self::DcNetWorkingParamEquipsList => "DCNetWorkingParam_Equips_List",
            Self::DcNetWorkingParamSkillStoneList => "DCNetWorkingParam_SkillStone_List",
            Self::DcNetWorkingParamPartnerList => "DCNetWorkingParam_Partner_List",
            Self::DcNetWorkingParamFormationList => "DCNetWorkingParam_Formation_List",
            Self::DcNetWorkingParamFeatList => "DCNetWorkingParam_Feat_List",
            Self::DcNetWorkingParamPortList => "DCNetWorkingParam_Port_List",
            Self::DcNetWorkingParamCheckinInfo => "DCNetWorkingParam_Checkin_Info",
            Self::DcNetWorkingParamCheckinReward => "DCNetWorkingParam_Checkin_Reward",
            Self::DcNetWorkingParamRolesChangeElement4Call => {
                "DCNetWorkingParam_Roles_ChangeElement4Call"
            }
            Self::DcNetWorkingParamUserGuideSave => "DCNetWorkingParam_UserGuide_Save",
            Self::DcNetWorkingParamUserGuideList => "DCNetWorkingParam_UserGuide_List",
            Self::DcNetWorkingParamGachaLogs => "DCNetWorkingParam_Gacha_Logs",
            Self::DcNetWorkingParamNaming => "DCNetWorkingParam_Naming",
            Self::DcNetWorkingParamSysInfo => "DCNetWorkingParam_SysInfo",
            Self::DcNetWorkingParamRoleSkinGetList => {
                "DCNetWorkingParam_RoleSkin_GetList"
            }
            Self::DcNetWorkingParamRolesChangeSkin => {
                "DCNetWorkingParam_Roles_ChangeSkin"
            }
            Self::DcNetWorkingParamExchangePhy => "DCNetWorkingParam_Exchange_Phy",
            Self::DcNetWorkingParamExchangeInfo => "DCNetWorkingParam_Exchange_Info",
            Self::DcNetWorkingParamUserChangeBannerGril => {
                "DCNetWorkingParam_User_ChangeBannerGril"
            }
            Self::DcNetWorkingParamSkillResetLv => "DCNetWorkingParam_Skill_ResetLv",
            Self::DcNetWorkingParamCheckinCheck => "DCNetWorkingParam_Checkin_Check",
            Self::DcNetWorkingParamTaskList => "DCNetWorkingParam_TaskList",
            Self::DcNetWorkingParamTask2Done => "DCNetWorkingParam_Task2Done",
            Self::DcNetWorkingParamInteractObjs => "DCNetWorkingParam_InteractObjs",
            Self::DcNetWorkingParamInteracting => "DCNetWorkingParam_Interacting",
            Self::DcNetWorkingParamTBoxInfoList => "DCNetWorkingParam_TBoxInfoList",
            Self::DcNetWorkingParamTBoxTakeReward => "DCNetWorkingParam_TBox_TakeReward",
            Self::DcNetWorkingParamRBoxInfoList => "DCNetWorkingParam_RBoxInfoList",
            Self::DcNetWorkingParamRBoxTakeReward => "DCNetWorkingParam_RBox_TakeReward",
            Self::DcNetWorkingParamTpMapInfoList => "DCNetWorkingParam_TPMapInfoList",
            Self::DcNetWorkingParamTpMapSet => "DCNetWorkingParam_TPMap_Set",
            Self::DcNetWorkingParamDenseFogList => "DCNetWorkingParam_DenseFogList",
            Self::DcNetWorkingParamDenseFogSet => "DCNetWorkingParam_DenseFog_Set",
            Self::DcNetWorkingParamPlayingPortSet => "DCNetWorkingParam_PlayingPort_Set",
            Self::DcNetWorkingParamPlayingPortGet => "DCNetWorkingParam_PlayingPort_Get",
            Self::DcNetWorkingParamFormationCurSet => {
                "DCNetWorkingParam_Formation_Cur_Set"
            }
            Self::DcNetWorkingParamFormationAdd => "DCNetWorkingParam_Formation_Add",
            Self::DcNetWorkingParamFormationDel => "DCNetWorkingParam_Formation_Del",
            Self::DcNetWorkingParamPartnerUnset => "DCNetWorkingParam_Partner_Unset",
            Self::DcNetWorkingParamDungeonStart => "DCNetWorkingParam_Dungeon_Start",
            Self::DcNetWorkingParamDungeonSett => "DCNetWorkingParam_Dungeon_Sett",
            Self::DcNetWorkingParamEquipsSwap => "DCNetWorkingParam_Equips_Swap",
            Self::DcNetWorkingParamPartnerSwap => "DCNetWorkingParam_Partner_Swap",
            Self::DcNetWorkingParamAlbumsList => "DCNetWorkingParam_Albums_List",
            Self::DcNetWorkingParamAlbumsSelect => "DCNetWorkingParam_Albums_Select",
            Self::DcNetWorkingParamLocalList => "DCNetWorkingParam_Local_List",
            Self::DcNetWorkingParamLocalSet => "DCNetWorkingParam_Local_Set",
            Self::DcNetWorkingParamTrialSave => "DCNetWorkingParam_Trial_Save",
            Self::DcNetWorkingParamTrialDone => "DCNetWorkingParam_Trial_Done",
            Self::DcNetWorkingParamTrialInfo => "DCNetWorkingParam_Trial_Info",
            Self::DcNetWorkingParamSmsList => "DCNetWorkingParam_SMS_List",
            Self::DcNetWorkingParamSmsRead => "DCNetWorkingParam_SMS_Read",
            Self::DcNetWorkingParamFavorList => "DCNetWorkingParam_Favor_List",
            Self::DcNetWorkingParamRegionInfo => "DCNetWorkingParam_Region_Info",
            Self::DcNetWorkingParamRegionTakeDailyReward => {
                "DCNetWorkingParam_Region_Take_Daily_Reward"
            }
            Self::DcNetWorkingParamRegionTakeTask => "DCNetWorkingParam_Region_Take_Task",
            Self::DcNetWorkingParamRolesMcSwitch => "DCNetWorkingParam_Roles_MC_Switch",
            Self::DcNetWorkingParamTaskGoalSet => "DCNetWorkingParam_Task_Goal_Set",
            Self::DcNetWorkingParamRegionList => "DCNetWorkingParam_Region_List",
            Self::DcNetWorkingParamFeatUnlock => "DCNetWorkingParam_Feat_Unlock",
            Self::DcNetWorkingParamMallBuy => "DCNetWorkingParam_Mall_Buy",
            Self::DcNetWorkingParamMallList => "DCNetWorkingParam_Mall_List",
            Self::DcNetWorkingParamSkillstonesSwap => {
                "DCNetWorkingParam_Skillstones_Swap"
            }
            Self::DcNetWorkingParamArchiveList => "DCNetWorkingParam_Archive_List",
            Self::DcNetWorkingParamTrialList => "DCNetWorkingParam_Trial_List",
            Self::DcNetWorkingParamTaskCycleList => "DCNetWorkingParam_TaskCycle_List",
            Self::DcNetWorkingParamTaskCycleTakeActivity => {
                "DCNetWorkingParam_TaskCycle_TakeActivity"
            }
            Self::DcNetWorkingParamTaskCycleTakeReward => {
                "DCNetWorkingParam_TaskCycle_TakeReward"
            }
            Self::DcNetWorkingParamItemsConvert => "DCNetWorkingParam_Items_Convert",
            Self::DcNetWorkingParamItemsSynthesis => "DCNetWorkingParam_Items_Synthesis",
            Self::DcNetWorkingParamAchiList => "DCNetWorkingParam_Achi_List",
            Self::DcNetWorkingParamAchiClaim => "DCNetWorkingParam_Achi_Claim",
            Self::DcNetWorkingParamActivityOpenList => {
                "DCNetWorkingParam_Activity_Open_List"
            }
            Self::DcNetWorkingParamActivityLevelUpList => {
                "DCNetWorkingParam_Activity_Level_Up_List"
            }
            Self::DcNetWorkingParamActivityLevelUpReward => {
                "DCNetWorkingParam_Activity_Level_Up_Reward"
            }
            Self::DcNetWorkingParamActivity7DayList => {
                "DCNetWorkingParam_Activity7Day_List"
            }
            Self::DcNetWorkingParamActivity7DayClaim => {
                "DCNetWorkingParam_Activity7Day_Claim"
            }
            Self::DcNetWorkingParamActivity7DayPointClaim => {
                "DCNetWorkingParam_Activity7Day_Point_Claim"
            }
            Self::DcNetWorkingParamCollectionList => "DCNetWorkingParam_Collection_List",
            Self::DcNetWorkingParamCollectionReward => {
                "DCNetWorkingParam_Collection_Reward"
            }
            Self::DcNetWorkingParamCollectionSuitRewardList => {
                "DCNetWorkingParam_Collection_Suit_Reward_List"
            }
            Self::DcNetWorkingParamCollectionSuitReward => {
                "DCNetWorkingParam_Collection_Suit_Reward"
            }
            Self::DcNetWorkingParamCollectionPlace => {
                "DCNetWorkingParam_Collection_Place"
            }
            Self::DcNetWorkingParamCollectionPlaceInfos => {
                "DCNetWorkingParam_Collection_Place_Infos"
            }
            Self::DcNetWorkingParamTalentLevelUp => "DCNetWorkingParam_Talent_LevelUp",
            Self::DcNetWorkingParamCityGuideSet => "DCNetWorkingParam_CityGuide_Set",
            Self::DcNetWorkingParamCityGuideList => "DCNetWorkingParam_CityGuide_List",
            Self::DcNetWorkingParamActivityBossChallengeSett => {
                "DCNetWorkingParam_Activity_Boss_Challenge_Sett"
            }
            Self::DcNetWorkingParamActivityBossChallengeInfo => {
                "DCNetWorkingParam_Activity_Boss_Challenge_Info"
            }
            Self::DcNetWorkingParamActivityBossChallengeReward => {
                "DCNetWorkingParam_Activity_Boss_Challenge_Reward"
            }
            Self::DcNetWorkingParamActivityBossChallengeRank => {
                "DCNetWorkingParam_Activity_Boss_Challenge_Rank"
            }
            Self::DcNetWorkingParamActivityChallengesList => {
                "DCNetWorkingParam_Activity_Challenges_List"
            }
            Self::DcNetWorkingParamActivityChallengesClaim => {
                "DCNetWorkingParam_Activity_Challenges_Claim"
            }
            Self::DcNetWorkingParamChallengesReport => {
                "DCNetWorkingParam_Challenges_Report"
            }
            Self::DcNetWorkingParamActivityChallengesPointClaim => {
                "DCNetWorkingParam_Activity_Challenges_Point_Claim"
            }
            Self::DcNetWorkingParamChallengesParkourReport => {
                "DCNetWorkingParam_Challenges_Parkour_Report"
            }
            Self::DcNetWorkingParamChallengesList => "DCNetWorkingParam_Challenges_List",
            Self::DcNetWorkingParamFavorAdd => "DCNetWorkingParam_Favor_Add",
            Self::DcNetWorkingParamFavorUseItem => "DCNetWorkingParam_Favor_Use_Item",
            Self::DcNetWorkingParamRougeStart => "DCNetWorkingParam_Rouge_Start",
            Self::DcNetWorkingParamRougeNodeReport => {
                "DCNetWorkingParam_Rouge_Node_Report"
            }
            Self::DcNetWorkingParamRougeEnter => "DCNetWorkingParam_Rouge_Enter",
            Self::DcNetWorkingParamRougeBossBoxOpen => {
                "DCNetWorkingParam_Rouge_BossBox_Open"
            }
            Self::DcNetWorkingParamRougeNpcSelectEffect => {
                "DCNetWorkingParam_Rouge_Npc_Select_Effect"
            }
            Self::DcNetWorkingParamRougeTradeBuy => "DCNetWorkingParam_Rouge_Trade_Buy",
            Self::DcNetWorkingParamRoleRankUpAward => {
                "DCNetWorkingParam_Role_RankUp_Award"
            }
            Self::DcNetWorkingParamRougeBuffSelect => {
                "DCNetWorkingParam_Rouge_Buff_Select"
            }
            Self::DcNetWorkingParamRougeCoinboxOpen => {
                "DCNetWorkingParam_Rouge_Coinbox_Open"
            }
            Self::DcNetWorkingParamRougeRest => "DCNetWorkingParam_Rouge_Rest",
            Self::DcNetWorkingParamRougeSubevtStoreBuy => {
                "DCNetWorkingParam_Rouge_Subevt_Store_Buy"
            }
            Self::DcNetWorkingParamRougeSubevtItem => {
                "DCNetWorkingParam_Rouge_Subevt_Item"
            }
            Self::DcNetWorkingParamRougeInfo => "DCNetWorkingParam_Rouge_Info",
            Self::DcNetWorkingParamRougeFinish => "DCNetWorkingParam_Rouge_Finish",
            Self::DcNetWorkingParamRougeItemUse => "DCNetWorkingParam_Rouge_Item_Use",
            Self::DcNetWorkingParamActivityBossChallengeStart => {
                "DCNetWorkingParam_Activity_Boss_Challenge_Start"
            }
            Self::DcNetWorkingParamTeamCoreList => "DCNetWorkingParam_TeamCore_List",
            Self::DcNetWorkingParamTeamCoreCompose => {
                "DCNetWorkingParam_TeamCore_Compose"
            }
            Self::DcNetWorkingParamTeamCoreLock => "DCNetWorkingParam_TeamCore_Lock",
            Self::DcNetWorkingParamTeamEquipList => "DCNetWorkingParam_TeamEquip_List",
            Self::DcNetWorkingParamTeamEquipEquip => "DCNetWorkingParam_TeamEquip_Equip",
            Self::DcNetWorkingParamTeamEquipUnEquip => {
                "DCNetWorkingParam_TeamEquip_UnEquip"
            }
            Self::DcNetWorkingParamTeamEquipSetCore => {
                "DCNetWorkingParam_TeamEquip_Set_Core"
            }
            Self::DcNetWorkingParamTeamEquipUnSetCore => {
                "DCNetWorkingParam_TeamEquip_UnSet_Core"
            }
            Self::DcNetWorkingParamTeamEquipLock => "DCNetWorkingParam_TeamEquip_Lock",
            Self::DcNetWorkingParamTeamEquipLvUp => "DCNetWorkingParam_TeamEquip_LvUp",
            Self::DcNetWorkingParamRougeBlessOpen => "DCNetWorkingParam_Rouge_Bless_Open",
            Self::DcNetWorkingParamMoreTeamChallengeList => {
                "DCNetWorkingParam_MoreTeamChallenge_List"
            }
            Self::DcNetWorkingParamMoreTeamChallengeSett => {
                "DCNetWorkingParam_MoreTeamChallenge_Sett"
            }
            Self::DcNetWorkingParamMoreTeamChallengeAward => {
                "DCNetWorkingParam_MoreTeamChallenge_Award"
            }
            Self::DcNetWorkingParamMoreTeamChallengeStart => {
                "DCNetWorkingParam_MoreTeamChallenge_Start"
            }
            Self::DcNetWorkingParamRougeList => "DCNetWorkingParam_Rouge_List",
            Self::DcNetWorkingParamRougeWaiveBuff => "DCNetWorkingParam_Rouge_WaiveBuff",
            Self::DcNetWorkingParamRougeRegenBuff => "DCNetWorkingParam_Rouge_RegenBuff",
            Self::DcNetWorkingParamRougeTechTree => "DCNetWorkingParam_Rouge_Tech_Tree",
            Self::DcNetWorkingParamRougeTechTake => "DCNetWorkingParam_Rouge_Tech_Take",
            Self::DcNetWorkingParamRougeScoreRewardClaim => {
                "DCNetWorkingParam_Rouge_Score_Reward_Claim"
            }
            Self::DcNetWorkingParamRougeFormSave => "DCNetWorkingParam_Rouge_Form_Save",
            Self::DcNetWorkingParamQuestionUrl => "DCNetWorkingParam_Question_URL",
            Self::DcNetWorkingParamRougeStatusSet => "DCNetWorkingParam_Rouge_Status_Set",
            Self::DcNetWorkingParamMonsterPoints => "DCNetWorkingParam_Monster_Points",
            Self::DcNetWorkingParamMonsterPointHit => {
                "DCNetWorkingParam_Monster_PointHit"
            }
            Self::DcNetWorkingParamGachaClaimExtra => {
                "DCNetWorkingParam_Gacha_ClaimExtra"
            }
            Self::DcNetWorkingParamGoldCoinList => "DCNetWorkingParam_GoldCoin_List",
            Self::DcNetWorkingParamGoldCoinCollect => {
                "DCNetWorkingParam_GoldCoin_Collect"
            }
            Self::DcNetWorkingParamCollectionResList => {
                "DCNetWorkingParam_CollectionRes_List"
            }
            Self::DcNetWorkingParamCollectionResCollect => {
                "DCNetWorkingParam_CollectionRes_Collect"
            }
            Self::DcNetWorkingParamEquipsRandomWordRefresh => {
                "DCNetWorkingParam_Equips_RandomWord_Refresh"
            }
            Self::DcNetWorkingParamEquipsRandomWordReplace => {
                "DCNetWorkingParam_Equips_RandomWord_Replace"
            }
            Self::DcNetWorkingParamGachaClaimCumReward => {
                "DCNetWorkingParam_Gacha_ClaimCumReward"
            }
            Self::DcNetWorkingParamGachaBufferClaim => {
                "DCNetWorkingParam_Gacha_Buffer_Claim"
            }
            Self::DcNetWorkingParamPartnerSkillUp => "DCNetWorkingParam_Partner_SkillUp",
            Self::DcNetWorkingParamRoleAttrList => "DCNetWorkingParam_RoleAttr_List",
            Self::DcNetWorkingParamRoleAttrSave => "DCNetWorkingParam_RoleAttr_Save",
            Self::DcNetWorkingParamRechargeList => "DCNetWorkingParam_Recharge_List",
            Self::DcNetWorkingParamDungeonList => "DCNetWorkingParam_Dungeon_List",
            Self::DcNetWorkingParamDungeonSweep => "DCNetWorkingParam_Dungeon_Sweep",
            Self::DcNetWorkingParamExchangeSbs2hhs => {
                "DCNetWorkingParam_Exchange_SBS2HHS"
            }
            Self::DcNetWorkingParamItemSelectReward => {
                "DCNetWorkingParam_Item_Select_Reward"
            }
            Self::DcNetWorkingParamActivityBossChallengeDailyReward => {
                "DCNetWorkingParam_Activity_Boss_Challenge_Daily_Reward"
            }
            Self::DcNetWorkingParamBattlePassInfo => "DCNetWorkingParam_BattlePass_Info",
            Self::DcNetWorkingParamBattlePassTasks => {
                "DCNetWorkingParam_BattlePass_Tasks"
            }
            Self::DcNetWorkingParamBattlePassTaskClaim => {
                "DCNetWorkingParam_BattlePass_Task_Claim"
            }
            Self::DcNetWorkingParamBattlePassClaim => {
                "DCNetWorkingParam_BattlePass_Claim"
            }
            Self::DcNetWorkingParamBattlePassLevelUp => {
                "DCNetWorkingParam_BattlePass_Level_Up"
            }
            Self::DcNetWorkingParamBossRushInfo => "DCNetWorkingParam_Boss_Rush_Info",
            Self::DcNetWorkingParamBossRushSett => "DCNetWorkingParam_Boss_Rush_Sett",
            Self::DcNetWorkingParamBossRushReward => "DCNetWorkingParam_Boss_Rush_Reward",
            Self::DcNetWorkingParamBossRushRank => "DCNetWorkingParam_Boss_Rush_Rank",
            Self::DcNetWorkingParamRiftStart => "DCNetWorkingParam_Rift_Start",
            Self::DcNetWorkingParamRiftNext => "DCNetWorkingParam_Rift_Next",
            Self::DcNetWorkingParamRiftReport => "DCNetWorkingParam_Rift_Report",
            Self::DcNetWorkingParamRiftDefeat => "DCNetWorkingParam_Rift_Defeat",
            Self::DcNetWorkingParamRiftSettlment => "DCNetWorkingParam_Rift_Settlment",
            Self::DcNetWorkingParamRiftRank => "DCNetWorkingParam_Rift_Rank",
            Self::DcNetWorkingParamRiftTask => "DCNetWorkingParam_Rift_Task",
            Self::DcNetWorkingParamRiftTaskClaim => "DCNetWorkingParam_Rift_Task_Claim",
            Self::DcNetWorkingParamRebateItemUse => "DCNetWorkingParam_Rebate_Item_Use",
            Self::DcNetWorkingParamRiftInfo => "DCNetWorkingParam_Rift_Info",
            Self::DcNetWorkingParamProfileList => "DCNetWorkingParam_Profile_List",
            Self::DcNetWorkingParamProfileSet => "DCNetWorkingParam_Profile_Set",
            Self::DcNetWorkingParamFriendsInfo => "DCNetWorkingParam_Friends_Info",
            Self::DcNetWorkingParamFriendGiftSend => "DCNetWorkingParam_Friend_Gift_Send",
            Self::DcNetWorkingParamFriendGiftClaim => {
                "DCNetWorkingParam_Friend_Gift_Claim"
            }
            Self::DcNetWorkingParamFriendsSearch => "DCNetWorkingParam_Friends_Search",
            Self::DcNetWorkingParamFriendsRequest => "DCNetWorkingParam_Friends_Request",
            Self::DcNetWorkingParamFriendsApprove => "DCNetWorkingParam_Friends_Approve",
            Self::DcNetWorkingParamFriendsDelete => "DCNetWorkingParam_Friends_Delete",
            Self::DcNetWorkingParamFriendsProfile => "DCNetWorkingParam_Friends_Profile",
            Self::DcNetWorkingParamBossRushResetTeam => {
                "DCNetWorkingParam_Boss_Rush_ResetTeam"
            }
            Self::DcNetWorkingParamVersionChallengeStart => {
                "DCNetWorkingParam_VersionChallenge_Start"
            }
            Self::DcNetWorkingParamVersionChallengeList => {
                "DCNetWorkingParam_VersionChallenge_List"
            }
            Self::DcNetWorkingParamVersionChallengeSett => {
                "DCNetWorkingParam_VersionChallenge_Sett"
            }
            Self::DcNetWorkingParamVersionChallengeAward => {
                "DCNetWorkingParam_VersionChallenge_Award"
            }
            Self::DcNetWorkingParamVersionChallengeStageList => {
                "DCNetWorkingParam_VersionChallenge_Stage_List"
            }
            Self::DcNetWorkingParamVersionTaskList => {
                "DCNetWorkingParam_Version_Task_List"
            }
            Self::DcNetWorkingParamVersionTaskClaim => {
                "DCNetWorkingParam_Version_Task_Claim"
            }
            Self::DcNetWorkingParamVersionActivityInfo => {
                "DCNetWorkingParam_Version_ActivityInfo"
            }
            Self::DcNetWorkingParamActivityLimitedLevelUpList => {
                "DCNetWorkingParam_Activity_Limited_Level_Up_List"
            }
            Self::DcNetWorkingParamActivityLimitedLevelUpReward => {
                "DCNetWorkingParam_Activity_Limited_Level_Up_Reward"
            }
            Self::DcNetWorkingParamMoreTeamChallengeGroupList => {
                "DCNetWorkingParam_MoreTeamChallenge_GroupList"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NOTIFY_NEVER_USED_ZERO" => Some(Self::NotifyNeverUsedZero),
            "DCNetWorkingCommon_Error" => Some(Self::DcNetWorkingCommonError),
            "DCNetWorkingParam_GM_Cmd" => Some(Self::DcNetWorkingParamGmCmd),
            "DCNetWorkingParam_Gacha_Do" => Some(Self::DcNetWorkingParamGachaDo),
            "DCNetWorkingParam_Emails_GetEmails" => {
                Some(Self::DcNetWorkingParamEmailsGetEmails)
            }
            "DCNetWorkingParam_Emails_TakeGift" => {
                Some(Self::DcNetWorkingParamEmailsTakeGift)
            }
            "DCNetWorkingParam_Emails_Delete" => {
                Some(Self::DcNetWorkingParamEmailsDelete)
            }
            "DCNetWorkingParam_Emails_Read" => Some(Self::DcNetWorkingParamEmailsRead),
            "DCNetWorkingParam_Equips_LevelUp" => {
                Some(Self::DcNetWorkingParamEquipsLevelUp)
            }
            "DCNetWorkingParam_Equips_Set" => Some(Self::DcNetWorkingParamEquipsSet),
            "DCNetWorkingParam_Equips_Unset" => Some(Self::DcNetWorkingParamEquipsUnset),
            "DCNetWorkingParam_Equips_Lock" => Some(Self::DcNetWorkingParamEquipsLock),
            "DCNetWorkingParam_Equips_EquipSetGroup" => {
                Some(Self::DcNetWorkingParamEquipsEquipSetGroup)
            }
            "DCNetWorkingParam_Equips_EquipGetGroup" => {
                Some(Self::DcNetWorkingParamEquipsEquipGetGroup)
            }
            "DCNetWorkingParam_Equips_EquipDelGroup" => {
                Some(Self::DcNetWorkingParamEquipsEquipDelGroup)
            }
            "DCNetWorkingParam_Equips_SetEquips" => {
                Some(Self::DcNetWorkingParamEquipsSetEquips)
            }
            "DCNetWorkingParam_Formation_Set" => {
                Some(Self::DcNetWorkingParamFormationSet)
            }
            "DCNetWorkingParam_Items_Get" => Some(Self::DcNetWorkingParamItemsGet),
            "DCNetWorkingParam_Items_UseItem" => {
                Some(Self::DcNetWorkingParamItemsUseItem)
            }
            "DCNetWorkingParam_Missons_List" => Some(Self::DcNetWorkingParamMissonsList),
            "DCNetWorkingParam_Missons_TakeReward" => {
                Some(Self::DcNetWorkingParamMissonsTakeReward)
            }
            "DCNetWorkingParam_Monsters_MonsterManual4Port" => {
                Some(Self::DcNetWorkingParamMonstersMonsterManual4Port)
            }
            "DCNetWorkingParam_Notice" => Some(Self::DcNetWorkingParamNotice),
            "DCNetWorkingParam_Ports_Start" => Some(Self::DcNetWorkingParamPortsStart),
            "DCNetWorkingParam_Reddot_List" => Some(Self::DcNetWorkingParamReddotList),
            "DCNetWorkingParam_Ports_Sett" => Some(Self::DcNetWorkingParamPortsSett),
            "DCNetWorkingParam_Reddot_Check" => Some(Self::DcNetWorkingParamReddotCheck),
            "DCNetWorkingParam_Roles_UserRoles" => {
                Some(Self::DcNetWorkingParamRolesUserRoles)
            }
            "DCNetWorkingParam_Roles_RankUp" => Some(Self::DcNetWorkingParamRolesRankUp),
            "DCNetWorkingParam_Roles_BrekUp" => Some(Self::DcNetWorkingParamRolesBrekUp),
            "DCNetWorkingParam_Roles_LevelUp" => {
                Some(Self::DcNetWorkingParamRolesLevelUp)
            }
            "DCNetWorkingParam_Roles_GetFetterRewards" => {
                Some(Self::DcNetWorkingParamRolesGetFetterRewards)
            }
            "DCNetWorkingParam_Roles_TakeFetterReward" => {
                Some(Self::DcNetWorkingParamRolesTakeFetterReward)
            }
            "DCNetWorkingParam_Roles_ChangeAppear" => {
                Some(Self::DcNetWorkingParamRolesChangeAppear)
            }
            "DCNetWorkingParam_Roles_ChangeElement" => {
                Some(Self::DcNetWorkingParamRolesChangeElement)
            }
            "DCNetWorkingParam_Shop_Sell" => Some(Self::DcNetWorkingParamShopSell),
            "DCNetWorkingParam_Skills_GetInfo" => {
                Some(Self::DcNetWorkingParamSkillsGetInfo)
            }
            "DCNetWorkingParam_Skills_LevelUp" => {
                Some(Self::DcNetWorkingParamSkillsLevelUp)
            }
            "DCNetWorkingParam_Skillstones_Set" => {
                Some(Self::DcNetWorkingParamSkillstonesSet)
            }
            "DCNetWorkingParam_Skillstones_Unset" => {
                Some(Self::DcNetWorkingParamSkillstonesUnset)
            }
            "DCNetWorkingParam_Skillstones_Lock" => {
                Some(Self::DcNetWorkingParamSkillstonesLock)
            }
            "DCNetWorkingParam_Partner_LvUp" => Some(Self::DcNetWorkingParamPartnerLvUp),
            "DCNetWorkingParam_Partner_Change" => {
                Some(Self::DcNetWorkingParamPartnerChange)
            }
            "DCNetWorkingParam_Partner_Lock" => Some(Self::DcNetWorkingParamPartnerLock),
            "DCNetWorkingParam_Partner_Impress" => {
                Some(Self::DcNetWorkingParamPartnerImpress)
            }
            "DCNetWorkingParam_Partner_Brek" => Some(Self::DcNetWorkingParamPartnerBrek),
            "DCNetWorkingParam_User_GetInfo" => Some(Self::DcNetWorkingParamUserGetInfo),
            "DCNetWorkingParam_User_GetPhyInfo" => {
                Some(Self::DcNetWorkingParamUserGetPhyInfo)
            }
            "DCNetWorkingParam_Shop_GetInfo" => Some(Self::DcNetWorkingParamShopGetInfo),
            "DCNetWorkingParam_Shop_SetShipTags" => {
                Some(Self::DcNetWorkingParamShopSetShipTags)
            }
            "DCNetWorkingParam_Shop_ShipTagRefresh" => {
                Some(Self::DcNetWorkingParamShopShipTagRefresh)
            }
            "DCNetWorkingParam_Shop_GetGoods" => {
                Some(Self::DcNetWorkingParamShopGetGoods)
            }
            "DCNetWorkingParam_Shop_Buy" => Some(Self::DcNetWorkingParamShopBuy),
            "DCNetWorkingParam_Gacha_GetList" => {
                Some(Self::DcNetWorkingParamGachaGetList)
            }
            "DCNetWorkingParam_Roles_Profile" => {
                Some(Self::DcNetWorkingParamRolesProfile)
            }
            "DCNetWorkingParam_Equips_List" => Some(Self::DcNetWorkingParamEquipsList),
            "DCNetWorkingParam_SkillStone_List" => {
                Some(Self::DcNetWorkingParamSkillStoneList)
            }
            "DCNetWorkingParam_Partner_List" => Some(Self::DcNetWorkingParamPartnerList),
            "DCNetWorkingParam_Formation_List" => {
                Some(Self::DcNetWorkingParamFormationList)
            }
            "DCNetWorkingParam_Feat_List" => Some(Self::DcNetWorkingParamFeatList),
            "DCNetWorkingParam_Port_List" => Some(Self::DcNetWorkingParamPortList),
            "DCNetWorkingParam_Checkin_Info" => Some(Self::DcNetWorkingParamCheckinInfo),
            "DCNetWorkingParam_Checkin_Reward" => {
                Some(Self::DcNetWorkingParamCheckinReward)
            }
            "DCNetWorkingParam_Roles_ChangeElement4Call" => {
                Some(Self::DcNetWorkingParamRolesChangeElement4Call)
            }
            "DCNetWorkingParam_UserGuide_Save" => {
                Some(Self::DcNetWorkingParamUserGuideSave)
            }
            "DCNetWorkingParam_UserGuide_List" => {
                Some(Self::DcNetWorkingParamUserGuideList)
            }
            "DCNetWorkingParam_Gacha_Logs" => Some(Self::DcNetWorkingParamGachaLogs),
            "DCNetWorkingParam_Naming" => Some(Self::DcNetWorkingParamNaming),
            "DCNetWorkingParam_SysInfo" => Some(Self::DcNetWorkingParamSysInfo),
            "DCNetWorkingParam_RoleSkin_GetList" => {
                Some(Self::DcNetWorkingParamRoleSkinGetList)
            }
            "DCNetWorkingParam_Roles_ChangeSkin" => {
                Some(Self::DcNetWorkingParamRolesChangeSkin)
            }
            "DCNetWorkingParam_Exchange_Phy" => Some(Self::DcNetWorkingParamExchangePhy),
            "DCNetWorkingParam_Exchange_Info" => {
                Some(Self::DcNetWorkingParamExchangeInfo)
            }
            "DCNetWorkingParam_User_ChangeBannerGril" => {
                Some(Self::DcNetWorkingParamUserChangeBannerGril)
            }
            "DCNetWorkingParam_Skill_ResetLv" => {
                Some(Self::DcNetWorkingParamSkillResetLv)
            }
            "DCNetWorkingParam_Checkin_Check" => {
                Some(Self::DcNetWorkingParamCheckinCheck)
            }
            "DCNetWorkingParam_TaskList" => Some(Self::DcNetWorkingParamTaskList),
            "DCNetWorkingParam_Task2Done" => Some(Self::DcNetWorkingParamTask2Done),
            "DCNetWorkingParam_InteractObjs" => Some(Self::DcNetWorkingParamInteractObjs),
            "DCNetWorkingParam_Interacting" => Some(Self::DcNetWorkingParamInteracting),
            "DCNetWorkingParam_TBoxInfoList" => Some(Self::DcNetWorkingParamTBoxInfoList),
            "DCNetWorkingParam_TBox_TakeReward" => {
                Some(Self::DcNetWorkingParamTBoxTakeReward)
            }
            "DCNetWorkingParam_RBoxInfoList" => Some(Self::DcNetWorkingParamRBoxInfoList),
            "DCNetWorkingParam_RBox_TakeReward" => {
                Some(Self::DcNetWorkingParamRBoxTakeReward)
            }
            "DCNetWorkingParam_TPMapInfoList" => {
                Some(Self::DcNetWorkingParamTpMapInfoList)
            }
            "DCNetWorkingParam_TPMap_Set" => Some(Self::DcNetWorkingParamTpMapSet),
            "DCNetWorkingParam_DenseFogList" => Some(Self::DcNetWorkingParamDenseFogList),
            "DCNetWorkingParam_DenseFog_Set" => Some(Self::DcNetWorkingParamDenseFogSet),
            "DCNetWorkingParam_PlayingPort_Set" => {
                Some(Self::DcNetWorkingParamPlayingPortSet)
            }
            "DCNetWorkingParam_PlayingPort_Get" => {
                Some(Self::DcNetWorkingParamPlayingPortGet)
            }
            "DCNetWorkingParam_Formation_Cur_Set" => {
                Some(Self::DcNetWorkingParamFormationCurSet)
            }
            "DCNetWorkingParam_Formation_Add" => {
                Some(Self::DcNetWorkingParamFormationAdd)
            }
            "DCNetWorkingParam_Formation_Del" => {
                Some(Self::DcNetWorkingParamFormationDel)
            }
            "DCNetWorkingParam_Partner_Unset" => {
                Some(Self::DcNetWorkingParamPartnerUnset)
            }
            "DCNetWorkingParam_Dungeon_Start" => {
                Some(Self::DcNetWorkingParamDungeonStart)
            }
            "DCNetWorkingParam_Dungeon_Sett" => Some(Self::DcNetWorkingParamDungeonSett),
            "DCNetWorkingParam_Equips_Swap" => Some(Self::DcNetWorkingParamEquipsSwap),
            "DCNetWorkingParam_Partner_Swap" => Some(Self::DcNetWorkingParamPartnerSwap),
            "DCNetWorkingParam_Albums_List" => Some(Self::DcNetWorkingParamAlbumsList),
            "DCNetWorkingParam_Albums_Select" => {
                Some(Self::DcNetWorkingParamAlbumsSelect)
            }
            "DCNetWorkingParam_Local_List" => Some(Self::DcNetWorkingParamLocalList),
            "DCNetWorkingParam_Local_Set" => Some(Self::DcNetWorkingParamLocalSet),
            "DCNetWorkingParam_Trial_Save" => Some(Self::DcNetWorkingParamTrialSave),
            "DCNetWorkingParam_Trial_Done" => Some(Self::DcNetWorkingParamTrialDone),
            "DCNetWorkingParam_Trial_Info" => Some(Self::DcNetWorkingParamTrialInfo),
            "DCNetWorkingParam_SMS_List" => Some(Self::DcNetWorkingParamSmsList),
            "DCNetWorkingParam_SMS_Read" => Some(Self::DcNetWorkingParamSmsRead),
            "DCNetWorkingParam_Favor_List" => Some(Self::DcNetWorkingParamFavorList),
            "DCNetWorkingParam_Region_Info" => Some(Self::DcNetWorkingParamRegionInfo),
            "DCNetWorkingParam_Region_Take_Daily_Reward" => {
                Some(Self::DcNetWorkingParamRegionTakeDailyReward)
            }
            "DCNetWorkingParam_Region_Take_Task" => {
                Some(Self::DcNetWorkingParamRegionTakeTask)
            }
            "DCNetWorkingParam_Roles_MC_Switch" => {
                Some(Self::DcNetWorkingParamRolesMcSwitch)
            }
            "DCNetWorkingParam_Task_Goal_Set" => Some(Self::DcNetWorkingParamTaskGoalSet),
            "DCNetWorkingParam_Region_List" => Some(Self::DcNetWorkingParamRegionList),
            "DCNetWorkingParam_Feat_Unlock" => Some(Self::DcNetWorkingParamFeatUnlock),
            "DCNetWorkingParam_Mall_Buy" => Some(Self::DcNetWorkingParamMallBuy),
            "DCNetWorkingParam_Mall_List" => Some(Self::DcNetWorkingParamMallList),
            "DCNetWorkingParam_Skillstones_Swap" => {
                Some(Self::DcNetWorkingParamSkillstonesSwap)
            }
            "DCNetWorkingParam_Archive_List" => Some(Self::DcNetWorkingParamArchiveList),
            "DCNetWorkingParam_Trial_List" => Some(Self::DcNetWorkingParamTrialList),
            "DCNetWorkingParam_TaskCycle_List" => {
                Some(Self::DcNetWorkingParamTaskCycleList)
            }
            "DCNetWorkingParam_TaskCycle_TakeActivity" => {
                Some(Self::DcNetWorkingParamTaskCycleTakeActivity)
            }
            "DCNetWorkingParam_TaskCycle_TakeReward" => {
                Some(Self::DcNetWorkingParamTaskCycleTakeReward)
            }
            "DCNetWorkingParam_Items_Convert" => {
                Some(Self::DcNetWorkingParamItemsConvert)
            }
            "DCNetWorkingParam_Items_Synthesis" => {
                Some(Self::DcNetWorkingParamItemsSynthesis)
            }
            "DCNetWorkingParam_Achi_List" => Some(Self::DcNetWorkingParamAchiList),
            "DCNetWorkingParam_Achi_Claim" => Some(Self::DcNetWorkingParamAchiClaim),
            "DCNetWorkingParam_Activity_Open_List" => {
                Some(Self::DcNetWorkingParamActivityOpenList)
            }
            "DCNetWorkingParam_Activity_Level_Up_List" => {
                Some(Self::DcNetWorkingParamActivityLevelUpList)
            }
            "DCNetWorkingParam_Activity_Level_Up_Reward" => {
                Some(Self::DcNetWorkingParamActivityLevelUpReward)
            }
            "DCNetWorkingParam_Activity7Day_List" => {
                Some(Self::DcNetWorkingParamActivity7DayList)
            }
            "DCNetWorkingParam_Activity7Day_Claim" => {
                Some(Self::DcNetWorkingParamActivity7DayClaim)
            }
            "DCNetWorkingParam_Activity7Day_Point_Claim" => {
                Some(Self::DcNetWorkingParamActivity7DayPointClaim)
            }
            "DCNetWorkingParam_Collection_List" => {
                Some(Self::DcNetWorkingParamCollectionList)
            }
            "DCNetWorkingParam_Collection_Reward" => {
                Some(Self::DcNetWorkingParamCollectionReward)
            }
            "DCNetWorkingParam_Collection_Suit_Reward_List" => {
                Some(Self::DcNetWorkingParamCollectionSuitRewardList)
            }
            "DCNetWorkingParam_Collection_Suit_Reward" => {
                Some(Self::DcNetWorkingParamCollectionSuitReward)
            }
            "DCNetWorkingParam_Collection_Place" => {
                Some(Self::DcNetWorkingParamCollectionPlace)
            }
            "DCNetWorkingParam_Collection_Place_Infos" => {
                Some(Self::DcNetWorkingParamCollectionPlaceInfos)
            }
            "DCNetWorkingParam_Talent_LevelUp" => {
                Some(Self::DcNetWorkingParamTalentLevelUp)
            }
            "DCNetWorkingParam_CityGuide_Set" => {
                Some(Self::DcNetWorkingParamCityGuideSet)
            }
            "DCNetWorkingParam_CityGuide_List" => {
                Some(Self::DcNetWorkingParamCityGuideList)
            }
            "DCNetWorkingParam_Activity_Boss_Challenge_Sett" => {
                Some(Self::DcNetWorkingParamActivityBossChallengeSett)
            }
            "DCNetWorkingParam_Activity_Boss_Challenge_Info" => {
                Some(Self::DcNetWorkingParamActivityBossChallengeInfo)
            }
            "DCNetWorkingParam_Activity_Boss_Challenge_Reward" => {
                Some(Self::DcNetWorkingParamActivityBossChallengeReward)
            }
            "DCNetWorkingParam_Activity_Boss_Challenge_Rank" => {
                Some(Self::DcNetWorkingParamActivityBossChallengeRank)
            }
            "DCNetWorkingParam_Activity_Challenges_List" => {
                Some(Self::DcNetWorkingParamActivityChallengesList)
            }
            "DCNetWorkingParam_Activity_Challenges_Claim" => {
                Some(Self::DcNetWorkingParamActivityChallengesClaim)
            }
            "DCNetWorkingParam_Challenges_Report" => {
                Some(Self::DcNetWorkingParamChallengesReport)
            }
            "DCNetWorkingParam_Activity_Challenges_Point_Claim" => {
                Some(Self::DcNetWorkingParamActivityChallengesPointClaim)
            }
            "DCNetWorkingParam_Challenges_Parkour_Report" => {
                Some(Self::DcNetWorkingParamChallengesParkourReport)
            }
            "DCNetWorkingParam_Challenges_List" => {
                Some(Self::DcNetWorkingParamChallengesList)
            }
            "DCNetWorkingParam_Favor_Add" => Some(Self::DcNetWorkingParamFavorAdd),
            "DCNetWorkingParam_Favor_Use_Item" => {
                Some(Self::DcNetWorkingParamFavorUseItem)
            }
            "DCNetWorkingParam_Rouge_Start" => Some(Self::DcNetWorkingParamRougeStart),
            "DCNetWorkingParam_Rouge_Node_Report" => {
                Some(Self::DcNetWorkingParamRougeNodeReport)
            }
            "DCNetWorkingParam_Rouge_Enter" => Some(Self::DcNetWorkingParamRougeEnter),
            "DCNetWorkingParam_Rouge_BossBox_Open" => {
                Some(Self::DcNetWorkingParamRougeBossBoxOpen)
            }
            "DCNetWorkingParam_Rouge_Npc_Select_Effect" => {
                Some(Self::DcNetWorkingParamRougeNpcSelectEffect)
            }
            "DCNetWorkingParam_Rouge_Trade_Buy" => {
                Some(Self::DcNetWorkingParamRougeTradeBuy)
            }
            "DCNetWorkingParam_Role_RankUp_Award" => {
                Some(Self::DcNetWorkingParamRoleRankUpAward)
            }
            "DCNetWorkingParam_Rouge_Buff_Select" => {
                Some(Self::DcNetWorkingParamRougeBuffSelect)
            }
            "DCNetWorkingParam_Rouge_Coinbox_Open" => {
                Some(Self::DcNetWorkingParamRougeCoinboxOpen)
            }
            "DCNetWorkingParam_Rouge_Rest" => Some(Self::DcNetWorkingParamRougeRest),
            "DCNetWorkingParam_Rouge_Subevt_Store_Buy" => {
                Some(Self::DcNetWorkingParamRougeSubevtStoreBuy)
            }
            "DCNetWorkingParam_Rouge_Subevt_Item" => {
                Some(Self::DcNetWorkingParamRougeSubevtItem)
            }
            "DCNetWorkingParam_Rouge_Info" => Some(Self::DcNetWorkingParamRougeInfo),
            "DCNetWorkingParam_Rouge_Finish" => Some(Self::DcNetWorkingParamRougeFinish),
            "DCNetWorkingParam_Rouge_Item_Use" => {
                Some(Self::DcNetWorkingParamRougeItemUse)
            }
            "DCNetWorkingParam_Activity_Boss_Challenge_Start" => {
                Some(Self::DcNetWorkingParamActivityBossChallengeStart)
            }
            "DCNetWorkingParam_TeamCore_List" => {
                Some(Self::DcNetWorkingParamTeamCoreList)
            }
            "DCNetWorkingParam_TeamCore_Compose" => {
                Some(Self::DcNetWorkingParamTeamCoreCompose)
            }
            "DCNetWorkingParam_TeamCore_Lock" => {
                Some(Self::DcNetWorkingParamTeamCoreLock)
            }
            "DCNetWorkingParam_TeamEquip_List" => {
                Some(Self::DcNetWorkingParamTeamEquipList)
            }
            "DCNetWorkingParam_TeamEquip_Equip" => {
                Some(Self::DcNetWorkingParamTeamEquipEquip)
            }
            "DCNetWorkingParam_TeamEquip_UnEquip" => {
                Some(Self::DcNetWorkingParamTeamEquipUnEquip)
            }
            "DCNetWorkingParam_TeamEquip_Set_Core" => {
                Some(Self::DcNetWorkingParamTeamEquipSetCore)
            }
            "DCNetWorkingParam_TeamEquip_UnSet_Core" => {
                Some(Self::DcNetWorkingParamTeamEquipUnSetCore)
            }
            "DCNetWorkingParam_TeamEquip_Lock" => {
                Some(Self::DcNetWorkingParamTeamEquipLock)
            }
            "DCNetWorkingParam_TeamEquip_LvUp" => {
                Some(Self::DcNetWorkingParamTeamEquipLvUp)
            }
            "DCNetWorkingParam_Rouge_Bless_Open" => {
                Some(Self::DcNetWorkingParamRougeBlessOpen)
            }
            "DCNetWorkingParam_MoreTeamChallenge_List" => {
                Some(Self::DcNetWorkingParamMoreTeamChallengeList)
            }
            "DCNetWorkingParam_MoreTeamChallenge_Sett" => {
                Some(Self::DcNetWorkingParamMoreTeamChallengeSett)
            }
            "DCNetWorkingParam_MoreTeamChallenge_Award" => {
                Some(Self::DcNetWorkingParamMoreTeamChallengeAward)
            }
            "DCNetWorkingParam_MoreTeamChallenge_Start" => {
                Some(Self::DcNetWorkingParamMoreTeamChallengeStart)
            }
            "DCNetWorkingParam_Rouge_List" => Some(Self::DcNetWorkingParamRougeList),
            "DCNetWorkingParam_Rouge_WaiveBuff" => {
                Some(Self::DcNetWorkingParamRougeWaiveBuff)
            }
            "DCNetWorkingParam_Rouge_RegenBuff" => {
                Some(Self::DcNetWorkingParamRougeRegenBuff)
            }
            "DCNetWorkingParam_Rouge_Tech_Tree" => {
                Some(Self::DcNetWorkingParamRougeTechTree)
            }
            "DCNetWorkingParam_Rouge_Tech_Take" => {
                Some(Self::DcNetWorkingParamRougeTechTake)
            }
            "DCNetWorkingParam_Rouge_Score_Reward_Claim" => {
                Some(Self::DcNetWorkingParamRougeScoreRewardClaim)
            }
            "DCNetWorkingParam_Rouge_Form_Save" => {
                Some(Self::DcNetWorkingParamRougeFormSave)
            }
            "DCNetWorkingParam_Question_URL" => Some(Self::DcNetWorkingParamQuestionUrl),
            "DCNetWorkingParam_Rouge_Status_Set" => {
                Some(Self::DcNetWorkingParamRougeStatusSet)
            }
            "DCNetWorkingParam_Monster_Points" => {
                Some(Self::DcNetWorkingParamMonsterPoints)
            }
            "DCNetWorkingParam_Monster_PointHit" => {
                Some(Self::DcNetWorkingParamMonsterPointHit)
            }
            "DCNetWorkingParam_Gacha_ClaimExtra" => {
                Some(Self::DcNetWorkingParamGachaClaimExtra)
            }
            "DCNetWorkingParam_GoldCoin_List" => {
                Some(Self::DcNetWorkingParamGoldCoinList)
            }
            "DCNetWorkingParam_GoldCoin_Collect" => {
                Some(Self::DcNetWorkingParamGoldCoinCollect)
            }
            "DCNetWorkingParam_CollectionRes_List" => {
                Some(Self::DcNetWorkingParamCollectionResList)
            }
            "DCNetWorkingParam_CollectionRes_Collect" => {
                Some(Self::DcNetWorkingParamCollectionResCollect)
            }
            "DCNetWorkingParam_Equips_RandomWord_Refresh" => {
                Some(Self::DcNetWorkingParamEquipsRandomWordRefresh)
            }
            "DCNetWorkingParam_Equips_RandomWord_Replace" => {
                Some(Self::DcNetWorkingParamEquipsRandomWordReplace)
            }
            "DCNetWorkingParam_Gacha_ClaimCumReward" => {
                Some(Self::DcNetWorkingParamGachaClaimCumReward)
            }
            "DCNetWorkingParam_Gacha_Buffer_Claim" => {
                Some(Self::DcNetWorkingParamGachaBufferClaim)
            }
            "DCNetWorkingParam_Partner_SkillUp" => {
                Some(Self::DcNetWorkingParamPartnerSkillUp)
            }
            "DCNetWorkingParam_RoleAttr_List" => {
                Some(Self::DcNetWorkingParamRoleAttrList)
            }
            "DCNetWorkingParam_RoleAttr_Save" => {
                Some(Self::DcNetWorkingParamRoleAttrSave)
            }
            "DCNetWorkingParam_Recharge_List" => {
                Some(Self::DcNetWorkingParamRechargeList)
            }
            "DCNetWorkingParam_Dungeon_List" => Some(Self::DcNetWorkingParamDungeonList),
            "DCNetWorkingParam_Dungeon_Sweep" => {
                Some(Self::DcNetWorkingParamDungeonSweep)
            }
            "DCNetWorkingParam_Exchange_SBS2HHS" => {
                Some(Self::DcNetWorkingParamExchangeSbs2hhs)
            }
            "DCNetWorkingParam_Item_Select_Reward" => {
                Some(Self::DcNetWorkingParamItemSelectReward)
            }
            "DCNetWorkingParam_Activity_Boss_Challenge_Daily_Reward" => {
                Some(Self::DcNetWorkingParamActivityBossChallengeDailyReward)
            }
            "DCNetWorkingParam_BattlePass_Info" => {
                Some(Self::DcNetWorkingParamBattlePassInfo)
            }
            "DCNetWorkingParam_BattlePass_Tasks" => {
                Some(Self::DcNetWorkingParamBattlePassTasks)
            }
            "DCNetWorkingParam_BattlePass_Task_Claim" => {
                Some(Self::DcNetWorkingParamBattlePassTaskClaim)
            }
            "DCNetWorkingParam_BattlePass_Claim" => {
                Some(Self::DcNetWorkingParamBattlePassClaim)
            }
            "DCNetWorkingParam_BattlePass_Level_Up" => {
                Some(Self::DcNetWorkingParamBattlePassLevelUp)
            }
            "DCNetWorkingParam_Boss_Rush_Info" => {
                Some(Self::DcNetWorkingParamBossRushInfo)
            }
            "DCNetWorkingParam_Boss_Rush_Sett" => {
                Some(Self::DcNetWorkingParamBossRushSett)
            }
            "DCNetWorkingParam_Boss_Rush_Reward" => {
                Some(Self::DcNetWorkingParamBossRushReward)
            }
            "DCNetWorkingParam_Boss_Rush_Rank" => {
                Some(Self::DcNetWorkingParamBossRushRank)
            }
            "DCNetWorkingParam_Rift_Start" => Some(Self::DcNetWorkingParamRiftStart),
            "DCNetWorkingParam_Rift_Next" => Some(Self::DcNetWorkingParamRiftNext),
            "DCNetWorkingParam_Rift_Report" => Some(Self::DcNetWorkingParamRiftReport),
            "DCNetWorkingParam_Rift_Defeat" => Some(Self::DcNetWorkingParamRiftDefeat),
            "DCNetWorkingParam_Rift_Settlment" => {
                Some(Self::DcNetWorkingParamRiftSettlment)
            }
            "DCNetWorkingParam_Rift_Rank" => Some(Self::DcNetWorkingParamRiftRank),
            "DCNetWorkingParam_Rift_Task" => Some(Self::DcNetWorkingParamRiftTask),
            "DCNetWorkingParam_Rift_Task_Claim" => {
                Some(Self::DcNetWorkingParamRiftTaskClaim)
            }
            "DCNetWorkingParam_Rebate_Item_Use" => {
                Some(Self::DcNetWorkingParamRebateItemUse)
            }
            "DCNetWorkingParam_Rift_Info" => Some(Self::DcNetWorkingParamRiftInfo),
            "DCNetWorkingParam_Profile_List" => Some(Self::DcNetWorkingParamProfileList),
            "DCNetWorkingParam_Profile_Set" => Some(Self::DcNetWorkingParamProfileSet),
            "DCNetWorkingParam_Friends_Info" => Some(Self::DcNetWorkingParamFriendsInfo),
            "DCNetWorkingParam_Friend_Gift_Send" => {
                Some(Self::DcNetWorkingParamFriendGiftSend)
            }
            "DCNetWorkingParam_Friend_Gift_Claim" => {
                Some(Self::DcNetWorkingParamFriendGiftClaim)
            }
            "DCNetWorkingParam_Friends_Search" => {
                Some(Self::DcNetWorkingParamFriendsSearch)
            }
            "DCNetWorkingParam_Friends_Request" => {
                Some(Self::DcNetWorkingParamFriendsRequest)
            }
            "DCNetWorkingParam_Friends_Approve" => {
                Some(Self::DcNetWorkingParamFriendsApprove)
            }
            "DCNetWorkingParam_Friends_Delete" => {
                Some(Self::DcNetWorkingParamFriendsDelete)
            }
            "DCNetWorkingParam_Friends_Profile" => {
                Some(Self::DcNetWorkingParamFriendsProfile)
            }
            "DCNetWorkingParam_Boss_Rush_ResetTeam" => {
                Some(Self::DcNetWorkingParamBossRushResetTeam)
            }
            "DCNetWorkingParam_VersionChallenge_Start" => {
                Some(Self::DcNetWorkingParamVersionChallengeStart)
            }
            "DCNetWorkingParam_VersionChallenge_List" => {
                Some(Self::DcNetWorkingParamVersionChallengeList)
            }
            "DCNetWorkingParam_VersionChallenge_Sett" => {
                Some(Self::DcNetWorkingParamVersionChallengeSett)
            }
            "DCNetWorkingParam_VersionChallenge_Award" => {
                Some(Self::DcNetWorkingParamVersionChallengeAward)
            }
            "DCNetWorkingParam_VersionChallenge_Stage_List" => {
                Some(Self::DcNetWorkingParamVersionChallengeStageList)
            }
            "DCNetWorkingParam_Version_Task_List" => {
                Some(Self::DcNetWorkingParamVersionTaskList)
            }
            "DCNetWorkingParam_Version_Task_Claim" => {
                Some(Self::DcNetWorkingParamVersionTaskClaim)
            }
            "DCNetWorkingParam_Version_ActivityInfo" => {
                Some(Self::DcNetWorkingParamVersionActivityInfo)
            }
            "DCNetWorkingParam_Activity_Limited_Level_Up_List" => {
                Some(Self::DcNetWorkingParamActivityLimitedLevelUpList)
            }
            "DCNetWorkingParam_Activity_Limited_Level_Up_Reward" => {
                Some(Self::DcNetWorkingParamActivityLimitedLevelUpReward)
            }
            "DCNetWorkingParam_MoreTeamChallenge_GroupList" => {
                Some(Self::DcNetWorkingParamMoreTeamChallengeGroupList)
            }
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NotifyId {
    NeverUsedZero = 0,
    DcNetWorkingNotifyPortsInfo = 10002,
    DcNetDataFeat = 10004,
    DcNetWorkingNotifyEmails = 10006,
    DcNetDataMissonInfo = 10008,
    DcNetWorkingNotifyReddots = 10010,
    DcNetWorkingNotifyRoleProfile = 10012,
    DcNetWorkingNotifyTick = 10014,
    DcNetWorkingNotifyQuesti = 10016,
    DcNetDataTaskChanged = 10018,
    DcNetDataAttrUpData = 10020,
    DcNetDataUnlockSKill = 10022,
    DcNetDataFormation = 10024,
    DcNetDataAlbums = 10026,
    DcNetDataSms = 10028,
    DcNetWorkingNotifyRegion = 10030,
    DcNetDataPhy = 10032,
    DcNetWorkingNotifyArchive = 10034,
    DcNetDataTrial = 10036,
    DcNetWorkingNotifyKickOut = 10038,
    DcNetWorkingNotifyAchi = 10040,
    DcNetWorkingNotifyTaskCycle = 10042,
    DcNetWorkingNotifyNewDay = 10044,
    DcNetWorkingNotifyAct7Day = 10046,
    DcNetWorkingNotifyInteractObjs = 10048,
    DcNetWorkingNotifyRoleAttrInfo = 10050,
    DcNetWorkingNotifyRecharge = 10052,
    DcNetWorkingNotifyRechargeMonthlyCard = 10054,
    DcNetWorkingNotifyMonthlyCardDailyReward = 10056,
    DcNetWorkingNotifyRechargeMall = 10058,
    DcNetWorkingNotifyWorldLevel = 10060,
    DcNetWorkingNotifyBattlePass = 10062,
    DcNetWorkingNotifyBattlePassTask = 10064,
    DcNetWorkingNotifyRiftTask = 10066,
    DcNetWorkingNotifyRedeemGiftCode = 10068,
    DcNetWorkingNotifyProfileExpire = 10070,
    DcNetWorkingNotifyFriends = 10072,
    DcNetWorkingNotifyProfileNew = 10074,
    DcNetWorkingNotifyVersionTask = 10076,
}
impl NotifyId {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NeverUsedZero => "NEVER_USED_ZERO",
            Self::DcNetWorkingNotifyPortsInfo => "DCNetWorkingNotify_PortsInfo",
            Self::DcNetDataFeat => "DCNetData_Feat",
            Self::DcNetWorkingNotifyEmails => "DCNetWorkingNotify_Emails",
            Self::DcNetDataMissonInfo => "DCNetData_MissonInfo",
            Self::DcNetWorkingNotifyReddots => "DCNetWorkingNotify_Reddots",
            Self::DcNetWorkingNotifyRoleProfile => "DCNetWorkingNotify_RoleProfile",
            Self::DcNetWorkingNotifyTick => "DCNetWorkingNotify_Tick",
            Self::DcNetWorkingNotifyQuesti => "DCNetWorkingNotify_Questi",
            Self::DcNetDataTaskChanged => "DCNetData_TaskChanged",
            Self::DcNetDataAttrUpData => "DCNetData_AttrUpData",
            Self::DcNetDataUnlockSKill => "DCNetData_UnlockSKill",
            Self::DcNetDataFormation => "DCNetData_Formation",
            Self::DcNetDataAlbums => "DCNetData_Albums",
            Self::DcNetDataSms => "DCNetData_SMS",
            Self::DcNetWorkingNotifyRegion => "DCNetWorkingNotify_Region",
            Self::DcNetDataPhy => "DCNetData_Phy",
            Self::DcNetWorkingNotifyArchive => "DCNetWorkingNotify_Archive",
            Self::DcNetDataTrial => "DCNetData_Trial",
            Self::DcNetWorkingNotifyKickOut => "DCNetWorkingNotify_KickOut",
            Self::DcNetWorkingNotifyAchi => "DCNetWorkingNotify_Achi",
            Self::DcNetWorkingNotifyTaskCycle => "DCNetWorkingNotify_TaskCycle",
            Self::DcNetWorkingNotifyNewDay => "DCNetWorkingNotify_NewDay",
            Self::DcNetWorkingNotifyAct7Day => "DCNetWorkingNotify_Act7Day",
            Self::DcNetWorkingNotifyInteractObjs => "DCNetWorkingNotify_InteractObjs",
            Self::DcNetWorkingNotifyRoleAttrInfo => "DCNetWorkingNotify_RoleAttrInfo",
            Self::DcNetWorkingNotifyRecharge => "DCNetWorkingNotify_Recharge",
            Self::DcNetWorkingNotifyRechargeMonthlyCard => {
                "DCNetWorkingNotify_Recharge_MonthlyCard"
            }
            Self::DcNetWorkingNotifyMonthlyCardDailyReward => {
                "DCNetWorkingNotify_MonthlyCard_DailyReward"
            }
            Self::DcNetWorkingNotifyRechargeMall => "DCNetWorkingNotify_Recharge_Mall",
            Self::DcNetWorkingNotifyWorldLevel => "DCNetWorkingNotify_World_Level",
            Self::DcNetWorkingNotifyBattlePass => "DCNetWorkingNotify_BattlePass",
            Self::DcNetWorkingNotifyBattlePassTask => {
                "DCNetWorkingNotify_BattlePass_Task"
            }
            Self::DcNetWorkingNotifyRiftTask => "DCNetWorkingNotify_Rift_Task",
            Self::DcNetWorkingNotifyRedeemGiftCode => {
                "DCNetWorkingNotify_Redeem_Gift_Code"
            }
            Self::DcNetWorkingNotifyProfileExpire => "DCNetWorkingNotify_Profile_Expire",
            Self::DcNetWorkingNotifyFriends => "DCNetWorkingNotify_Friends",
            Self::DcNetWorkingNotifyProfileNew => "DCNetWorkingNotify_Profile_New",
            Self::DcNetWorkingNotifyVersionTask => "DCNetWorkingNotify_Version_Task",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NEVER_USED_ZERO" => Some(Self::NeverUsedZero),
            "DCNetWorkingNotify_PortsInfo" => Some(Self::DcNetWorkingNotifyPortsInfo),
            "DCNetData_Feat" => Some(Self::DcNetDataFeat),
            "DCNetWorkingNotify_Emails" => Some(Self::DcNetWorkingNotifyEmails),
            "DCNetData_MissonInfo" => Some(Self::DcNetDataMissonInfo),
            "DCNetWorkingNotify_Reddots" => Some(Self::DcNetWorkingNotifyReddots),
            "DCNetWorkingNotify_RoleProfile" => Some(Self::DcNetWorkingNotifyRoleProfile),
            "DCNetWorkingNotify_Tick" => Some(Self::DcNetWorkingNotifyTick),
            "DCNetWorkingNotify_Questi" => Some(Self::DcNetWorkingNotifyQuesti),
            "DCNetData_TaskChanged" => Some(Self::DcNetDataTaskChanged),
            "DCNetData_AttrUpData" => Some(Self::DcNetDataAttrUpData),
            "DCNetData_UnlockSKill" => Some(Self::DcNetDataUnlockSKill),
            "DCNetData_Formation" => Some(Self::DcNetDataFormation),
            "DCNetData_Albums" => Some(Self::DcNetDataAlbums),
            "DCNetData_SMS" => Some(Self::DcNetDataSms),
            "DCNetWorkingNotify_Region" => Some(Self::DcNetWorkingNotifyRegion),
            "DCNetData_Phy" => Some(Self::DcNetDataPhy),
            "DCNetWorkingNotify_Archive" => Some(Self::DcNetWorkingNotifyArchive),
            "DCNetData_Trial" => Some(Self::DcNetDataTrial),
            "DCNetWorkingNotify_KickOut" => Some(Self::DcNetWorkingNotifyKickOut),
            "DCNetWorkingNotify_Achi" => Some(Self::DcNetWorkingNotifyAchi),
            "DCNetWorkingNotify_TaskCycle" => Some(Self::DcNetWorkingNotifyTaskCycle),
            "DCNetWorkingNotify_NewDay" => Some(Self::DcNetWorkingNotifyNewDay),
            "DCNetWorkingNotify_Act7Day" => Some(Self::DcNetWorkingNotifyAct7Day),
            "DCNetWorkingNotify_InteractObjs" => {
                Some(Self::DcNetWorkingNotifyInteractObjs)
            }
            "DCNetWorkingNotify_RoleAttrInfo" => {
                Some(Self::DcNetWorkingNotifyRoleAttrInfo)
            }
            "DCNetWorkingNotify_Recharge" => Some(Self::DcNetWorkingNotifyRecharge),
            "DCNetWorkingNotify_Recharge_MonthlyCard" => {
                Some(Self::DcNetWorkingNotifyRechargeMonthlyCard)
            }
            "DCNetWorkingNotify_MonthlyCard_DailyReward" => {
                Some(Self::DcNetWorkingNotifyMonthlyCardDailyReward)
            }
            "DCNetWorkingNotify_Recharge_Mall" => {
                Some(Self::DcNetWorkingNotifyRechargeMall)
            }
            "DCNetWorkingNotify_World_Level" => Some(Self::DcNetWorkingNotifyWorldLevel),
            "DCNetWorkingNotify_BattlePass" => Some(Self::DcNetWorkingNotifyBattlePass),
            "DCNetWorkingNotify_BattlePass_Task" => {
                Some(Self::DcNetWorkingNotifyBattlePassTask)
            }
            "DCNetWorkingNotify_Rift_Task" => Some(Self::DcNetWorkingNotifyRiftTask),
            "DCNetWorkingNotify_Redeem_Gift_Code" => {
                Some(Self::DcNetWorkingNotifyRedeemGiftCode)
            }
            "DCNetWorkingNotify_Profile_Expire" => {
                Some(Self::DcNetWorkingNotifyProfileExpire)
            }
            "DCNetWorkingNotify_Friends" => Some(Self::DcNetWorkingNotifyFriends),
            "DCNetWorkingNotify_Profile_New" => Some(Self::DcNetWorkingNotifyProfileNew),
            "DCNetWorkingNotify_Version_Task" => {
                Some(Self::DcNetWorkingNotifyVersionTask)
            }
            _ => None,
        }
    }
}
