use serde::Deserialize;

use super::TablePair;

#[derive(Debug, Deserialize)]
pub struct CultivationConstants {
    #[serde(rename = "PHY_REPLY_TIME")]
    pub heat_regeneration_interval: i32,
    #[serde(rename = "INITIAL_RESOURCE")]
    pub initial_resource: Vec<TablePair<i32>>,
    #[serde(rename = "INITIAL_MAID")]
    pub initial_maid: Vec<i32>,
    #[serde(rename = "INITIAL_PROFILE_FRAME")]
    pub initial_profile_frame: i32,
    #[serde(rename = "INITIAL_PROFILE_TITLE")]
    pub initial_profile_title: i32,
    #[serde(rename = "INITIAL_PROFILE_CARD")]
    pub initial_profile_card: i32,
    #[serde(rename = "DEFAULT_MAIN_MAID_SEX")]
    pub default_main_maid_sex: Vec<i32>,
    #[serde(rename = "TEAM_QUANTITY_MAX")]
    pub custom_formation_count: i32,
    #[serde(rename = "TEAM_ROUTINE_NUM")]
    pub fixed_formation_count: i32,
    #[serde(rename = "TEAM_MAX_MAID_NUMBER")]
    pub formation_member_limit: i32,
    #[serde(rename = "MAX_HEAT_LIMIT")]
    pub heat_limit: i32,
    #[serde(rename = "MAX_RARITY")]
    pub max_role_resonance: i32,
    #[serde(rename = "HEAT")]
    pub heat_item_id: i32,
    #[serde(rename = "COIN")]
    pub coin_item_id: i32,
    #[serde(rename = "DIAMOND")]
    pub diamond_item_id: i32,
    #[serde(rename = "STAMP")]
    pub stamp_item_id: i32,
    #[serde(rename = "DIAMOND_DRAWCOST_EXCHANGE")]
    pub diamonds_per_stamp: i32,
    #[serde(rename = "HEAT_RESTORE_PRICE")]
    pub heat_restore_costs: Vec<TablePair<i32>>,
    #[serde(rename = "HEAT_RESTORE_POINT")]
    pub heat_restore_amounts: Vec<TablePair<i32>>,
    #[serde(rename = "MAX_HEAT_EXCHANGE_LIMIT")]
    pub daily_heat_exchange_limit: i32,
    #[serde(rename = "REFRESH_TIME")]
    pub daily_reset_hour: i32,
    #[serde(rename = "DAILY_TOUCH_FAVOR_LIMIT")]
    pub daily_favor_touch_limit: i32,
    #[serde(rename = "DAILY_TOUCH_FAVOR_NUM")]
    pub favor_per_touch: i32,
    #[serde(rename = "WEEK_DUNGEON_LIMIT")]
    pub weekly_dungeon_limit: i32,
    #[serde(rename = "TASK_REGION_MAX_NUMBER")]
    pub max_region_tasks: i32,
    #[serde(rename = "TASK_REGION_TICKET_MAX")]
    pub region_ticket_limit: i32,
    #[serde(rename = "TASK_REGION_TICKET_DAILY")]
    pub daily_region_tickets: i32,
    #[serde(rename = "TASK_REGION_TYPE_MIN")]
    pub min_region_task_types: i32,
    #[serde(rename = "MAID_EXP_GOLD_COST")]
    pub role_exp_gold_rate: f32,
    #[serde(rename = "MAID_EXP_ITEM")]
    pub role_exp_items: Vec<i32>,
    #[serde(rename = "EQUIP_EXP_GOLD_COST")]
    pub equipment_exp_gold_rate: f32,
    #[serde(rename = "EQUIP_EXP_ITEM")]
    pub equipment_exp_items: Vec<i32>,
    #[serde(rename = "PARTNER_EXP_ITEM")]
    pub partner_exp_items: Vec<i32>,
    #[serde(rename = "WEAPON_EXP_SCALE")]
    pub partner_exp_refund_rate: f32,
    #[serde(rename = "EQUIP_EXP_SCALE")]
    pub equipment_exp_refund_rate: f32,
    #[serde(rename = "BREAK_EQUIP_LIMIT")]
    pub equipment_disassembly_limit: i32,
    #[serde(rename = "BREAK_PARTNER_LIMIT")]
    pub partner_disassembly_limit: i32,
    #[serde(rename = "PARTNER_EXP_GOLD_COST")]
    pub partner_exp_gold_rate: f32,
    #[serde(rename = "EQUIP_WORD_EXTRA_LIMIT")]
    pub extra_equipment_word_limit: i32,
    #[serde(rename = "BATTLE_PASS_LV_PRICE")]
    pub battle_pass_level_price: i32,
    #[serde(rename = "BOSSRUSH_REWARD_DELAY_TIME")]
    pub boss_rush_reward_delay_hours: i32,
    #[serde(rename = "MONTHCARD_DAILY")]
    pub monthly_card_daily_rewards: Vec<TablePair<i32>>,
    #[serde(rename = "MONTHCARD_DAY")]
    pub monthly_card_days: i32,
    #[serde(rename = "MONTHCARD_DAY_MAX")]
    pub monthly_card_max_days: i32,
    #[serde(rename = "DRAW_TIMES_REWARD_NEW")]
    pub new_pool_cumulative_draw_target: i32,
    #[serde(rename = "DRAW_TIMES_REWARD_NORMAL")]
    pub cumulative_draw_target: i32,
    #[serde(rename = "DRAW_TIMES_REWARD")]
    pub cumulative_draw_rewards: Vec<i32>,
    pub rename_cost: Vec<TablePair<i32>>,
    pub ticket_item_id: i32,
    pub ticket_initial: i32,
    #[serde(rename = "enter_cost")]
    pub rift_entry_cost: i32,
    pub friend_maximum: i32,
    pub friend_gift: Vec<TablePair<i32>>,
    pub friend_gift_maximum: i32,
}
